// Code generated by drel. DO NOT EDIT.

package db

import (
	"github.com/alternayte/drel"
	orders "github.com/alternayte/drel/examples/uuid-keys/orders"
)

type DB struct {
	*drel.Engine
	Orders *orders.OrderRepository
}

func Open(dsn string, opts ...drel.Option) (*DB, error) {
	engine, err := drel.NewEngine(dsn, opts...)
	if err != nil {
		return nil, err
	}
	return &DB{
		Engine: engine,
		Orders: &orders.OrderRepository{Repository: drel.NewRepository(engine, orders.OrderMeta)},
	}, nil
}

// UnitOfWork is a change-tracking work session with typed, tracked
// repositories. Load through uow.<Model>, stage with Add/Remove, then
// SaveChanges to flush everything in a single transaction.
type UnitOfWork struct {
	*drel.UnitOfWork
	Orders *orders.UoWOrderRepository
}

// NewUnitOfWork starts a new change-tracking work session.
func (db *DB) NewUnitOfWork() *UnitOfWork {
	uow := db.Engine.NewUnitOfWork()
	return &UnitOfWork{
		UnitOfWork: uow,
		Orders:     &orders.UoWOrderRepository{UoWRepository: drel.NewUoWRepository(uow, orders.OrderMeta)},
	}
}
