// Code generated by drel. DO NOT EDIT.

package models

import (
	"context"
	"time"

	"github.com/alternayte/drel"
)

var Tasks = struct {
	ID        drel.OrderedColumn[int]
	Title     drel.StringColumn
	Done      drel.BoolColumn
	Priority  drel.OrderedColumn[int]
	CreatedAt drel.Column[time.Time]
	UpdatedAt drel.Column[time.Time]
}{
	ID:        drel.NewOrderedCol[int]("id"),
	Title:     drel.NewStringCol("title"),
	Done:      drel.NewBoolCol("done"),
	Priority:  drel.NewOrderedCol[int]("priority"),
	CreatedAt: drel.NewCol[time.Time]("created_at"),
	UpdatedAt: drel.NewCol[time.Time]("updated_at"),
}

func scanTask(row drel.Row) (*Task, error) {
	p := &Task{}
	idPtr, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	err := row.Scan(idPtr, &p.Title, &p.Done, &p.Priority, createdAtPtr, updatedAtPtr)
	if err != nil {
		return nil, err
	}
	return p, nil
}

type taskSnapshot struct {
	Title    string
	Done     bool
	Priority int
}

func snapshotTask(p *Task) any {
	return taskSnapshot{Title: p.Title, Done: p.Done, Priority: p.Priority}
}

func diffTask(p *Task, snap any) []drel.FieldChange {
	s := snap.(taskSnapshot)
	var changes []drel.FieldChange
	if p.Title != s.Title {
		changes = append(changes, drel.FieldChange{Column: "title", Value: p.Title})
	}
	if p.Done != s.Done {
		changes = append(changes, drel.FieldChange{Column: "done", Value: p.Done})
	}
	if p.Priority != s.Priority {
		changes = append(changes, drel.FieldChange{Column: "priority", Value: p.Priority})
	}
	return changes
}

func taskPKValue(p *Task) any {
	return p.ID()
}

func taskColumnValue(p *Task, idx int) any {
	switch idx {
	case 0:
		return p.ID()
	case 1:
		return p.Title
	case 2:
		return p.Done
	case 3:
		return p.Priority
	case 4:
		return p.CreatedAt()
	case 5:
		return p.UpdatedAt()
	}
	return nil
}

func taskInsertColumns(p *Task) ([]string, []any) {
	return []string{"title", "done", "priority"}, []any{p.Title, p.Done, p.Priority}
}

func taskScanReturning(p *Task, row drel.Row) error {
	idPtr, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	return row.Scan(idPtr, createdAtPtr, updatedAtPtr)
}

var TaskMeta = drel.ModelMeta[Task]{
	Table:         "tasks",
	Columns:       []string{"id", "title", "done", "priority", "created_at", "updated_at"},
	PKColumn:      "id",
	Scan:          scanTask,
	Snapshot:      snapshotTask,
	Diff:          diffTask,
	PKValue:       taskPKValue,
	InsertColumns: taskInsertColumns,
	ScanReturning: taskScanReturning,
	ColumnValue:   taskColumnValue,
}

type TaskRepository struct {
	*drel.Repository[Task]
}

func (r *TaskRepository) FindByID(ctx context.Context, id int) (*Task, error) {
	return r.Find(ctx, id)
}

type TxTaskRepository struct {
	*drel.TxRepository[Task]
}

func (r *TxTaskRepository) FindByID(ctx context.Context, id int) (*Task, error) {
	return r.Find(ctx, id)
}
