package drel

import (
	"sync"

	"github.com/google/uuid"
)

// KeyStrategy selects how a model's primary key is produced.
type KeyStrategy uint8

const (
	// KeyAutoIncrement uses a database-generated key (SERIAL / AUTOINCREMENT)
	// read back after INSERT. This is the default for integer primary keys and
	// is the historical behavior.
	KeyAutoIncrement KeyStrategy = iota
	// KeyAppAssigned uses a key known before INSERT — generated by a registered
	// generator (e.g. UUIDv7) or set by application code. The key is written as
	// part of the INSERT and is never read back.
	KeyAppAssigned
)

// UUIDv7Key returns a fresh time-ordered UUIDv7 as an any, suitable as a
// ModelMeta.GenerateKey value. It is the default generator for uuid.UUID keys.
func UUIDv7Key() any {
	u, err := uuid.NewV7()
	if err != nil {
		// NewV7 only errors if the system RNG fails; fall back to v4.
		u = uuid.New()
	}
	return u
}

// keyConfig is the per-table key behavior consulted at Add/insert time.
type keyConfig struct {
	Strategy KeyStrategy
	Generate func() any // nil => key must be set by application code
}

var (
	keyConfigMu sync.RWMutex
	keyConfigs  = map[string]keyConfig{}
)

func setKeyConfig(table string, cfg keyConfig) {
	keyConfigMu.Lock()
	defer keyConfigMu.Unlock()
	keyConfigs[table] = cfg
}

func keyConfigFor(table string) (keyConfig, bool) {
	keyConfigMu.RLock()
	defer keyConfigMu.RUnlock()
	cfg, ok := keyConfigs[table]
	return cfg, ok
}

func clearKeyConfig(table string) {
	keyConfigMu.Lock()
	defer keyConfigMu.Unlock()
	delete(keyConfigs, table)
}
