// Code generated by drel. DO NOT EDIT.

package db

import (
	"github.com/alternayte/drel"
	catalog "github.com/alternayte/drel/examples/observability/catalog"
)

type DB struct {
	*drel.Engine
	Products *catalog.ProductRepository
}

func Open(dsn string, opts ...drel.Option) (*DB, error) {
	engine, err := drel.NewEngine(dsn, opts...)
	if err != nil {
		return nil, err
	}
	return &DB{
		Engine:   engine,
		Products: &catalog.ProductRepository{Repository: drel.NewRepository(engine, catalog.ProductMeta)},
	}, nil
}

// UnitOfWork is a change-tracking work session with typed, tracked
// repositories. Load through uow.<Model>, stage with Add/Remove, then
// SaveChanges to flush everything in a single transaction.
type UnitOfWork struct {
	*drel.UnitOfWork
	Products *catalog.UoWProductRepository
}

// NewUnitOfWork starts a new change-tracking work session.
func (db *DB) NewUnitOfWork() *UnitOfWork {
	uow := db.Engine.NewUnitOfWork()
	return &UnitOfWork{
		UnitOfWork: uow,
		Products:   &catalog.UoWProductRepository{UoWRepository: drel.NewUoWRepository(uow, catalog.ProductMeta)},
	}
}
