// Code generated by drel. DO NOT EDIT.

package db

import (
	"github.com/alternayte/drel"
	logs "github.com/alternayte/drel/examples/bulk-ops/logs"
)

type DB struct {
	*drel.Engine
	LogEntries *drel.Repository[logs.LogEntry]
}

func Open(dsn string, opts ...drel.Option) (*DB, error) {
	engine, err := drel.NewEngine(dsn, opts...)
	if err != nil {
		return nil, err
	}
	return &DB{
		Engine: engine,
		LogEntries: drel.NewRepository(engine, logs.LogEntryMeta),
	}, nil
}
