// Code generated by drel. DO NOT EDIT.

package db

import (
	"github.com/alternayte/drel"
	logs "github.com/alternayte/drel/examples/bulk-ops/logs"
)

type DB struct {
	*drel.Engine
	LogEntries *logs.LogEntryRepository
}

func Open(dsn string, opts ...drel.Option) (*DB, error) {
	engine, err := drel.NewEngine(dsn, opts...)
	if err != nil {
		return nil, err
	}
	return &DB{
		Engine:     engine,
		LogEntries: &logs.LogEntryRepository{Repository: drel.NewRepository(engine, logs.LogEntryMeta)},
	}, nil
}

// UnitOfWork is a change-tracking work session with typed, tracked
// repositories. Load through uow.<Model>, stage with Add/Remove, then
// SaveChanges to flush everything in a single transaction.
type UnitOfWork struct {
	*drel.UnitOfWork
	LogEntries *logs.UoWLogEntryRepository
}

// NewUnitOfWork starts a new change-tracking work session.
func (db *DB) NewUnitOfWork() *UnitOfWork {
	uow := db.Engine.NewUnitOfWork()
	return &UnitOfWork{
		UnitOfWork: uow,
		LogEntries: &logs.UoWLogEntryRepository{UoWRepository: drel.NewUoWRepository(uow, logs.LogEntryMeta)},
	}
}
