// Code generated by drel. DO NOT EDIT.

package models

import (
	"context"
	"time"

	"github.com/alternayte/drel"
)

var Accounts = struct {
	ID        drel.OrderedColumn[int]
	Email     drel.Column[Email]
	Balance   drel.Column[Cents]
	CreatedAt drel.Column[time.Time]
	UpdatedAt drel.Column[time.Time]
}{
	ID:        drel.NewOrderedCol[int]("id"),
	Email:     drel.NewCol[Email]("email"),
	Balance:   drel.NewCol[Cents]("balance"),
	CreatedAt: drel.NewCol[time.Time]("created_at"),
	UpdatedAt: drel.NewCol[time.Time]("updated_at"),
}

func scanAccount(row drel.Row) (*Account, error) {
	p := &Account{}
	idPtr, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	// email is a nullable value object: Scan(nil)->zero, Value()==nil for zero->NULL
	err := row.Scan(idPtr, &p.email, &p.balance, createdAtPtr, updatedAtPtr)
	if err != nil {
		return nil, err
	}
	return p, nil
}

type accountSnapshot struct {
	email   Email
	balance Cents
}

func snapshotAccount(p *Account) any {
	return accountSnapshot{email: p.email, balance: p.balance}
}

func diffAccount(p *Account, snap any) []drel.FieldChange {
	s := snap.(accountSnapshot)
	var changes []drel.FieldChange
	if p.email != s.email {
		changes = append(changes, drel.FieldChange{Column: "email", Value: p.email})
	}
	if p.balance != s.balance {
		changes = append(changes, drel.FieldChange{Column: "balance", Value: p.balance})
	}
	return changes
}

func accountPKValue(p *Account) any {
	return p.ID()
}

func accountColumnValue(p *Account, idx int) any {
	switch idx {
	case 0:
		return p.ID()
	case 1:
		return p.email
	case 2:
		return p.balance
	case 3:
		return p.CreatedAt()
	case 4:
		return p.UpdatedAt()
	}
	return nil
}

func accountInsertColumns(p *Account) ([]string, []any) {
	return []string{"email", "balance"}, []any{p.email, p.balance}
}

func accountScanReturning(p *Account, row drel.Row) error {
	idPtr, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	return row.Scan(idPtr, createdAtPtr, updatedAtPtr)
}

func accountNormalizeKey(v any) any {
	return drel.NormalizeIntKey(v)
}

var AccountMeta = drel.ModelMeta[Account]{
	Table:         "accounts",
	Columns:       []string{"id", "email", "balance", "created_at", "updated_at"},
	PKColumn:      "id",
	Scan:          scanAccount,
	Snapshot:      snapshotAccount,
	Diff:          diffAccount,
	PKValue:       accountPKValue,
	InsertColumns: accountInsertColumns,
	ScanReturning: accountScanReturning,
	ColumnValue:   accountColumnValue,
	NormalizeKey:  accountNormalizeKey,
}

type AccountRepository struct {
	*drel.Repository[Account]
}

func (r *AccountRepository) FindByID(ctx context.Context, id int) (*Account, error) {
	return r.Find(ctx, id)
}

type TxAccountRepository struct {
	*drel.TxRepository[Account]
}

func (r *TxAccountRepository) FindByID(ctx context.Context, id int) (*Account, error) {
	return r.Find(ctx, id)
}

type UoWAccountRepository struct {
	*drel.UoWRepository[Account]
}

func (r *UoWAccountRepository) FindByID(ctx context.Context, id int) (*Account, error) {
	return r.Find(ctx, id)
}
