// Code generated by drel. DO NOT EDIT.

package models

import (
	"context"

	"github.com/alternayte/drel"
)

var UserAccounts = struct {
	ID        drel.OrderedColumn[int]
	Email     drel.ComparableColumn[Email]
	Balance   drel.ComparableColumn[Cents]
	CreatedAt drel.TimeColumn
	UpdatedAt drel.TimeColumn
}{
	ID:        drel.NewOrderedCol[int]("id"),
	Email:     drel.NewComparableCol[Email]("email"),
	Balance:   drel.NewComparableCol[Cents]("balance"),
	CreatedAt: drel.NewTimeCol("created_at"),
	UpdatedAt: drel.NewTimeCol("updated_at"),
}

func scanUseraccount(row drel.Row) (*UserAccount, error) {
	p := &UserAccount{}
	idPtr, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	// email is a nullable value object: Scan(nil)->zero, Value()==nil for zero->NULL
	err := row.Scan(idPtr, &p.email, &p.balance, createdAtPtr, updatedAtPtr)
	if err != nil {
		return nil, err
	}
	return p, nil
}

type useraccountSnapshot struct {
	email   Email
	balance Cents
}

func snapshotUseraccount(p *UserAccount) any {
	return useraccountSnapshot{email: p.email, balance: p.balance}
}

func diffUseraccount(p *UserAccount, snap any) []drel.FieldChange {
	s := snap.(useraccountSnapshot)
	var changes []drel.FieldChange
	if p.email != s.email {
		changes = append(changes, drel.FieldChange{Column: "email", Value: p.email})
	}
	if p.balance != s.balance {
		changes = append(changes, drel.FieldChange{Column: "balance", Value: p.balance})
	}
	return changes
}

func useraccountPKValue(p *UserAccount) any {
	return p.ID()
}

func useraccountColumnValue(p *UserAccount, idx int) any {
	switch idx {
	case 0:
		return p.ID()
	case 1:
		return p.email
	case 2:
		return p.balance
	case 3:
		return p.CreatedAt()
	case 4:
		return p.UpdatedAt()
	}
	return nil
}

func useraccountInsertColumns(p *UserAccount) ([]string, []any) {
	return []string{"email", "balance"}, []any{p.email, p.balance}
}

func useraccountScanReturning(p *UserAccount, row drel.Row) error {
	idPtr, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	return row.Scan(idPtr, createdAtPtr, updatedAtPtr)
}

func useraccountNormalizeKey(v any) any {
	return drel.NormalizeIntKey(v)
}

var UserAccountMeta = drel.ModelMeta[UserAccount]{
	Table:         "user_accounts",
	Columns:       []string{"id", "email", "balance", "created_at", "updated_at"},
	PKColumn:      "id",
	Scan:          scanUseraccount,
	Snapshot:      snapshotUseraccount,
	Diff:          diffUseraccount,
	PKValue:       useraccountPKValue,
	InsertColumns: useraccountInsertColumns,
	ScanReturning: useraccountScanReturning,
	ColumnValue:   useraccountColumnValue,
	NormalizeKey:  useraccountNormalizeKey,
}

type UserAccountRepository struct {
	*drel.Repository[UserAccount]
}

func (r *UserAccountRepository) FindByID(ctx context.Context, id int) (*UserAccount, error) {
	return r.Find(ctx, id)
}

type TxUserAccountRepository struct {
	*drel.TxRepository[UserAccount]
}

func (r *TxUserAccountRepository) FindByID(ctx context.Context, id int) (*UserAccount, error) {
	return r.Find(ctx, id)
}

type UoWUserAccountRepository struct {
	*drel.UoWRepository[UserAccount]
}

func (r *UoWUserAccountRepository) FindByID(ctx context.Context, id int) (*UserAccount, error) {
	return r.Find(ctx, id)
}
