package codegen

import (
	"fmt"
	"path"
	"sort"
	"strings"
	"unicode"
)

// exportName capitalises the first letter of a name.
func exportName(name string) string {
	if name == "" {
		return name
	}
	rs := []rune(name)
	rs[0] = unicode.ToUpper(rs[0])
	return string(rs)
}

// fieldDisplayType returns the type name to use in generated code.
// Same-package types are unqualified; external types are package-qualified using resolved aliases.
func fieldDisplayType(f FieldInfo, aliases map[string]string) string {
	if f.TypePkgPath != "" && f.LocalGoType != "" {
		alias := path.Base(f.TypePkgPath)
		if a, ok := aliases[f.TypePkgPath]; ok {
			alias = a
		}
		qualified := alias + "." + f.LocalGoType
		if f.IsPointer {
			return "*" + qualified
		}
		return qualified
	}
	if f.LocalGoType != "" {
		if f.IsPointer {
			return "*" + f.LocalGoType
		}
		return f.LocalGoType
	}
	return f.GoType
}

func resolvePKDisplay(m ModelInfo, aliases map[string]string) string {
	if m.PKTypePkg == "" {
		return m.PKType
	}
	alias := path.Base(m.PKTypePkg)
	if a, ok := aliases[m.PKTypePkg]; ok {
		alias = a
	}
	parts := strings.SplitN(m.PKType, ".", 2)
	if len(parts) == 2 {
		return alias + "." + parts[1]
	}
	return m.PKType
}

// columnTypeName returns the drel column type for a Go type.
func columnTypeName(goType string) string {
	switch goType {
	case "string":
		return "drel.StringColumn"
	case "bool":
		return "drel.BoolColumn"
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64",
		"float32", "float64":
		return fmt.Sprintf("drel.OrderedColumn[%s]", goType)
	default:
		return fmt.Sprintf("drel.Column[%s]", goType)
	}
}

// columnConstructor returns the drel constructor call for a Go type and column name.
func columnConstructor(goType, colName string) string {
	switch goType {
	case "string":
		return fmt.Sprintf("drel.NewStringCol(%q)", colName)
	case "bool":
		return fmt.Sprintf("drel.NewBoolCol(%q)", colName)
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64",
		"float32", "float64":
		return fmt.Sprintf("drel.NewOrderedCol[%s](%q)", goType, colName)
	default:
		return fmt.Sprintf("drel.NewCol[%s](%q)", goType, colName)
	}
}

func buildModelImportAliases(m ModelInfo) map[string]string {
	aliases := make(map[string]string)
	aliasCount := make(map[string]int)

	addPkg := func(pkgPath string) {
		if pkgPath == "" || pkgPath == "time" || pkgPath == m.PkgPath {
			return
		}
		if _, ok := aliases[pkgPath]; ok {
			return
		}
		base := path.Base(pkgPath)
		aliasCount[base]++
		if aliasCount[base] == 1 {
			aliases[pkgPath] = base
		} else {
			aliases[pkgPath] = fmt.Sprintf("%s%d", base, aliasCount[base])
		}
	}

	if m.PKTypePkg != "" {
		addPkg(m.PKTypePkg)
	}
	for _, f := range columnFields(m.Fields) {
		if f.TypePkgPath != "" {
			addPkg(f.TypePkgPath)
		}
	}
	return aliases
}

func emitImports(b *strings.Builder, m ModelInfo, extAliases map[string]string) {
	stdImports := map[string]bool{"context": true, "time": true}

	if m.PKTypePkg == "time" {
		stdImports["time"] = true
	}
	for _, f := range columnFields(m.Fields) {
		if f.TypePkgPath == "time" {
			stdImports["time"] = true
		}
	}

	b.WriteString("import (\n")
	var stdList []string
	for pkg := range stdImports {
		stdList = append(stdList, pkg)
	}
	sort.Strings(stdList)
	for _, pkg := range stdList {
		b.WriteString(fmt.Sprintf("\t%q\n", pkg))
	}

	b.WriteString("\n\t\"github.com/alternayte/drel\"\n")

	var extList []string
	for pkg := range extAliases {
		extList = append(extList, pkg)
	}
	sort.Strings(extList)
	for _, pkg := range extList {
		alias := extAliases[pkg]
		b.WriteString(fmt.Sprintf("\t%s %q\n", alias, pkg))
	}
	b.WriteString(")\n\n")
}

// columnFields returns only the fields that map to database columns (non-relationship fields).
func columnFields(fields []FieldInfo) []FieldInfo {
	var out []FieldInfo
	for _, f := range fields {
		if f.ColumnName != "" {
			out = append(out, f)
		}
	}
	return out
}

// EmitModelFileChecked generates the per-model file, returning an error if the
// model uses unsupported features.
func EmitModelFileChecked(m ModelInfo) (string, error) {
	for _, f := range m.Fields {
		if f.IsMultiColVO {
			return "", fmt.Errorf("drel: model %q field %q implements MultiColumnMapper but multi-column value objects are not yet supported in code generation. Use a single-column ColumnMapper instead, or remove the MultiColumnMapper implementation", m.Name, f.Name)
		}
	}
	return EmitModelFile(m), nil
}

// EmitModelFile generates the complete per-model _drel.go file content.
func EmitModelFile(m ModelInfo) string {
	var b strings.Builder
	lower := strings.ToLower(m.Name)
	varPlural := pluralize(m.Name)

	aliases := buildModelImportAliases(m)

	// Header
	b.WriteString("// Code generated by drel. DO NOT EDIT.\n\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", m.PkgName))
	emitImports(&b, m, aliases)

	// --- Column references ---
	emitColumnRefs(&b, m, varPlural, aliases)

	// --- All columns list ---
	allCols := allColumns(m)

	// --- Scan function ---
	emitScanFunc(&b, m, lower, allCols)

	// --- Snapshot struct + function ---
	emitSnapshot(&b, m, lower, aliases)

	// --- Diff function ---
	emitDiff(&b, m, lower)

	// --- PK value ---
	b.WriteString(fmt.Sprintf("func %sPKValue(p *%s) any {\n\treturn p.ID()\n}\n\n", lower, m.Name))

	// --- Column value ---
	emitColumnValue(&b, m, lower, allCols)

	// --- Insert columns ---
	emitInsertColumns(&b, m, lower)

	// --- Scan returning ---
	emitScanReturning(&b, m, lower)

	// --- ModelMeta ---
	emitMeta(&b, m, lower, varPlural, allCols)

	// --- Typed repository wrappers ---
	emitTypedRepos(&b, m)

	return b.String()
}

func emitColumnRefs(b *strings.Builder, m ModelInfo, varPlural string, aliases map[string]string) {
	colFields := columnFields(m.Fields)
	// Struct type definition
	b.WriteString(fmt.Sprintf("var %s = struct {\n", varPlural))
	// ID column - always present, derived from PKType
	pkDisplay := resolvePKDisplay(m, aliases)
	b.WriteString(fmt.Sprintf("\tID %s\n", columnTypeName(pkDisplay)))
	for _, f := range colFields {
		b.WriteString(fmt.Sprintf("\t%s %s\n", exportName(f.Name), columnTypeName(fieldDisplayType(f, aliases))))
	}
	if m.HasSoftDelete {
		b.WriteString("\tDeletedAt drel.Column[*time.Time]\n")
	}
	if m.HasVersioned {
		b.WriteString("\tVersion drel.OrderedColumn[int]\n")
	}
	if m.HasAudit {
		b.WriteString("\tCreatedBy drel.StringColumn\n")
		b.WriteString("\tUpdatedBy drel.StringColumn\n")
	}
	b.WriteString("\tCreatedAt drel.Column[time.Time]\n")
	b.WriteString("\tUpdatedAt drel.Column[time.Time]\n")
	b.WriteString("}{\n")

	// Struct literal values
	b.WriteString(fmt.Sprintf("\tID: %s,\n", columnConstructor(pkDisplay, "id")))
	for _, f := range colFields {
		b.WriteString(fmt.Sprintf("\t%s: %s,\n", exportName(f.Name), columnConstructor(fieldDisplayType(f, aliases), f.ColumnName)))
	}
	if m.HasSoftDelete {
		b.WriteString("\tDeletedAt: drel.NewCol[*time.Time](\"deleted_at\"),\n")
	}
	if m.HasVersioned {
		b.WriteString("\tVersion: drel.NewOrderedCol[int](\"version\"),\n")
	}
	if m.HasAudit {
		b.WriteString("\tCreatedBy: drel.NewStringCol(\"created_by\"),\n")
		b.WriteString("\tUpdatedBy: drel.NewStringCol(\"updated_by\"),\n")
	}
	b.WriteString("\tCreatedAt: drel.NewCol[time.Time](\"created_at\"),\n")
	b.WriteString("\tUpdatedAt: drel.NewCol[time.Time](\"updated_at\"),\n")
	b.WriteString("}\n\n")
}

// allColumns returns the full ordered list of column names for this model.
func allColumns(m ModelInfo) []string {
	cols := []string{"id"}
	for _, f := range columnFields(m.Fields) {
		cols = append(cols, f.ColumnName)
	}
	if m.HasSoftDelete {
		cols = append(cols, "deleted_at")
	}
	if m.HasVersioned {
		cols = append(cols, "version")
	}
	if m.HasAudit {
		cols = append(cols, "created_by", "updated_by")
	}
	cols = append(cols, "created_at", "updated_at")
	return cols
}

func emitScanFunc(b *strings.Builder, m ModelInfo, lower string, allCols []string) {
	b.WriteString(fmt.Sprintf("func scan%s(row drel.Row) (*%s, error) {\n", exportName(lower), m.Name))
	b.WriteString(fmt.Sprintf("\tp := &%s{}\n", m.Name))
	b.WriteString("\tidPtr, createdAtPtr, updatedAtPtr := p.ScanPtrs()\n")
	if m.HasAudit {
		b.WriteString("\tcreatedByPtr, updatedByPtr := p.AuditPtrs()\n")
	}

	// Build scan args
	var scanArgs []string
	scanArgs = append(scanArgs, "idPtr")
	for _, f := range columnFields(m.Fields) {
		scanArgs = append(scanArgs, fmt.Sprintf("&p.%s", f.Name))
	}
	if m.HasSoftDelete {
		scanArgs = append(scanArgs, "p.DeletedAtPtr()")
	}
	if m.HasVersioned {
		scanArgs = append(scanArgs, "p.VersionPtr()")
	}
	if m.HasAudit {
		scanArgs = append(scanArgs, "createdByPtr", "updatedByPtr")
	}
	scanArgs = append(scanArgs, "createdAtPtr", "updatedAtPtr")

	b.WriteString(fmt.Sprintf("\terr := row.Scan(%s)\n", strings.Join(scanArgs, ", ")))
	b.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
	b.WriteString("\treturn p, nil\n}\n\n")
}

func emitSnapshot(b *strings.Builder, m ModelInfo, lower string, aliases map[string]string) {
	colFields := columnFields(m.Fields)
	// Snapshot struct
	b.WriteString(fmt.Sprintf("type %sSnapshot struct {\n", lower))
	for _, f := range colFields {
		b.WriteString(fmt.Sprintf("\t%s %s\n", f.Name, fieldDisplayType(f, aliases)))
	}
	b.WriteString("}\n\n")

	// Snapshot function
	b.WriteString(fmt.Sprintf("func snapshot%s(p *%s) any {\n", exportName(lower), m.Name))
	b.WriteString(fmt.Sprintf("\treturn %sSnapshot{", lower))
	for i, f := range colFields {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(fmt.Sprintf("%s: p.%s", f.Name, f.Name))
	}
	b.WriteString("}\n}\n\n")
}

func emitDiff(b *strings.Builder, m ModelInfo, lower string) {
	b.WriteString(fmt.Sprintf("func diff%s(p *%s, snap any) []drel.FieldChange {\n", exportName(lower), m.Name))
	b.WriteString(fmt.Sprintf("\ts := snap.(%sSnapshot)\n", lower))
	b.WriteString("\tvar changes []drel.FieldChange\n")
	for _, f := range columnFields(m.Fields) {
		b.WriteString(fmt.Sprintf("\tif p.%s != s.%s {\n", f.Name, f.Name))
		b.WriteString(fmt.Sprintf("\t\tchanges = append(changes, drel.FieldChange{Column: %q, Value: p.%s})\n", f.ColumnName, f.Name))
		b.WriteString("\t}\n")
	}
	b.WriteString("\treturn changes\n}\n\n")
}

func emitColumnValue(b *strings.Builder, m ModelInfo, lower string, allCols []string) {
	b.WriteString(fmt.Sprintf("func %sColumnValue(p *%s, idx int) any {\n", lower, m.Name))
	b.WriteString("\tswitch idx {\n")

	idx := 0
	// id (index 0)
	b.WriteString(fmt.Sprintf("\tcase %d:\n\t\treturn p.ID()\n", idx))
	idx++

	// User-defined columns
	for _, f := range columnFields(m.Fields) {
		b.WriteString(fmt.Sprintf("\tcase %d:\n\t\treturn p.%s\n", idx, f.Name))
		idx++
	}

	// Optional embeds
	if m.HasSoftDelete {
		b.WriteString(fmt.Sprintf("\tcase %d:\n\t\treturn p.DeletedAt()\n", idx))
		idx++
	}
	if m.HasVersioned {
		b.WriteString(fmt.Sprintf("\tcase %d:\n\t\treturn p.Version()\n", idx))
		idx++
	}
	if m.HasAudit {
		b.WriteString(fmt.Sprintf("\tcase %d:\n\t\treturn p.CreatedBy()\n", idx))
		idx++
		b.WriteString(fmt.Sprintf("\tcase %d:\n\t\treturn p.UpdatedBy()\n", idx))
		idx++
	}

	// created_at, updated_at
	b.WriteString(fmt.Sprintf("\tcase %d:\n\t\treturn p.CreatedAt()\n", idx))
	idx++
	b.WriteString(fmt.Sprintf("\tcase %d:\n\t\treturn p.UpdatedAt()\n", idx))

	b.WriteString("\t}\n\treturn nil\n}\n\n")
}

func emitInsertColumns(b *strings.Builder, m ModelInfo, lower string) {
	b.WriteString(fmt.Sprintf("func %sInsertColumns(p *%s) ([]string, []any) {\n", lower, m.Name))
	var colNames []string
	var colVals []string
	for _, f := range columnFields(m.Fields) {
		colNames = append(colNames, fmt.Sprintf("%q", f.ColumnName))
		colVals = append(colVals, fmt.Sprintf("p.%s", f.Name))
	}
	if m.HasAudit {
		colNames = append(colNames, `"created_by"`, `"updated_by"`)
		colVals = append(colVals, "p.CreatedBy()", "p.UpdatedBy()")
	}
	b.WriteString(fmt.Sprintf("\treturn []string{%s}, []any{%s}\n", strings.Join(colNames, ", "), strings.Join(colVals, ", ")))
	b.WriteString("}\n\n")
}

func emitScanReturning(b *strings.Builder, m ModelInfo, lower string) {
	b.WriteString(fmt.Sprintf("func %sScanReturning(p *%s, row drel.Row) error {\n", lower, m.Name))
	b.WriteString("\tidPtr, createdAtPtr, updatedAtPtr := p.ScanPtrs()\n")
	b.WriteString("\treturn row.Scan(idPtr, createdAtPtr, updatedAtPtr)\n")
	b.WriteString("}\n\n")
}

func emitTypedRepos(b *strings.Builder, m ModelInfo) {
	pkType := m.PKType

	b.WriteString(fmt.Sprintf("\ntype %sRepository struct {\n", m.Name))
	b.WriteString(fmt.Sprintf("\t*drel.Repository[%s]\n", m.Name))
	b.WriteString("}\n\n")

	b.WriteString(fmt.Sprintf("func (r *%sRepository) FindByID(ctx context.Context, id %s) (*%s, error) {\n", m.Name, pkType, m.Name))
	b.WriteString("\treturn r.Find(ctx, id)\n")
	b.WriteString("}\n\n")

	b.WriteString(fmt.Sprintf("type Tx%sRepository struct {\n", m.Name))
	b.WriteString(fmt.Sprintf("\t*drel.TxRepository[%s]\n", m.Name))
	b.WriteString("}\n\n")

	b.WriteString(fmt.Sprintf("func (r *Tx%sRepository) FindByID(ctx context.Context, id %s) (*%s, error) {\n", m.Name, pkType, m.Name))
	b.WriteString("\treturn r.Find(ctx, id)\n")
	b.WriteString("}\n")
}

func emitMeta(b *strings.Builder, m ModelInfo, lower, varPlural string, allCols []string) {
	b.WriteString(fmt.Sprintf("var %sMeta = drel.ModelMeta[%s]{\n", m.Name, m.Name))
	b.WriteString(fmt.Sprintf("\tTable:   %q,\n", m.TableName))

	quoted := make([]string, len(allCols))
	for i, c := range allCols {
		quoted[i] = fmt.Sprintf("%q", c)
	}
	b.WriteString(fmt.Sprintf("\tColumns: []string{%s},\n", strings.Join(quoted, ", ")))
	b.WriteString("\tPKColumn: \"id\",\n")
	b.WriteString(fmt.Sprintf("\tScan:          scan%s,\n", exportName(lower)))
	b.WriteString(fmt.Sprintf("\tSnapshot:      snapshot%s,\n", exportName(lower)))
	b.WriteString(fmt.Sprintf("\tDiff:          diff%s,\n", exportName(lower)))
	b.WriteString(fmt.Sprintf("\tPKValue:       %sPKValue,\n", lower))
	b.WriteString(fmt.Sprintf("\tInsertColumns: %sInsertColumns,\n", lower))
	b.WriteString(fmt.Sprintf("\tScanReturning: %sScanReturning,\n", lower))
	b.WriteString(fmt.Sprintf("\tColumnValue:   %sColumnValue,\n", lower))

	if m.HasSoftDelete {
		b.WriteString("\tHasSoftDelete: true,\n")
		b.WriteString("\tFilters: []drel.NamedFilter{drel.SoftDeleteFilter},\n")
	}
	if m.HasVersioned {
		b.WriteString("\tHasVersioned: true,\n")
		b.WriteString(fmt.Sprintf("\tVersionValue: func(p *%s) int { return p.Version() },\n", m.Name))
		b.WriteString(fmt.Sprintf("\tSetVersion:   func(p *%s, v int) { *p.VersionPtr() = v },\n", m.Name))
	}
	if m.HasAudit {
		b.WriteString("\tHasAudit: true,\n")
		b.WriteString(fmt.Sprintf("\tAuditSetCreate: func(p *%s, actor string) {\n", m.Name))
		b.WriteString("\t\tcreatedByPtr, updatedByPtr := p.AuditPtrs()\n")
		b.WriteString("\t\t*createdByPtr = actor\n")
		b.WriteString("\t\t*updatedByPtr = actor\n")
		b.WriteString("\t},\n")
		b.WriteString(fmt.Sprintf("\tAuditSetUpdate: func(p *%s, actor string) {\n", m.Name))
		b.WriteString("\t\t_, updatedByPtr := p.AuditPtrs()\n")
		b.WriteString("\t\t*updatedByPtr = actor\n")
		b.WriteString("\t},\n")
	}

	b.WriteString("}\n")
}
