package codegen

import (
	"fmt"
	"path"
	"strings"
)

// EmitDBFile generates the aggregated DB struct file that wires up all
// repositories. dbPkgName is the Go package name for the output file (e.g. "db").
func EmitDBFile(models []ModelInfo, dbPkgName string) string {
	var b strings.Builder

	// Header
	b.WriteString("// Code generated by drel. DO NOT EDIT.\n\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", dbPkgName))

	// Imports
	b.WriteString("import (\n")
	b.WriteString("\t\"github.com/alternayte/drel\"\n")
	seen := make(map[string]bool)
	for _, m := range models {
		if !seen[m.PkgPath] {
			seen[m.PkgPath] = true
			alias := path.Base(m.PkgPath)
			b.WriteString(fmt.Sprintf("\t%s %q\n", alias, m.PkgPath))
		}
	}
	b.WriteString(")\n\n")

	// DB struct
	b.WriteString("type DB struct {\n")
	b.WriteString("\t*drel.Engine\n")
	for _, m := range models {
		alias := path.Base(m.PkgPath)
		fieldName := pluralize(m.Name)
		b.WriteString(fmt.Sprintf("\t%s *drel.Repository[%s.%s]\n", fieldName, alias, m.Name))
	}
	b.WriteString("}\n\n")

	// Open function
	b.WriteString("func Open(dsn string, opts ...drel.Option) (*DB, error) {\n")
	b.WriteString("\tengine, err := drel.NewEngine(dsn, opts...)\n")
	b.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
	b.WriteString("\treturn &DB{\n")
	b.WriteString("\t\tEngine: engine,\n")
	for _, m := range models {
		alias := path.Base(m.PkgPath)
		fieldName := pluralize(m.Name)
		b.WriteString(fmt.Sprintf("\t\t%s: drel.NewRepository(engine, %s.%sMeta),\n", fieldName, alias, m.Name))
	}
	b.WriteString("\t}, nil\n")
	b.WriteString("}\n")

	return b.String()
}
