package codegen

import (
	"fmt"
	"path"
	"strings"
)

// EmitDBFile generates the aggregated DB struct file that wires up all
// repositories. dbPkgName is the Go package name for the output file (e.g. "db").
func EmitDBFile(models []ModelInfo, dbPkgName string) string {
	var b strings.Builder

	// Build deduplicated import aliases: map pkgPath -> alias
	aliases := resolveImportAliases(models)

	// Header
	b.WriteString("// Code generated by drel. DO NOT EDIT.\n\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", dbPkgName))

	// Imports
	b.WriteString("import (\n")
	b.WriteString("\t\"github.com/alternayte/drel\"\n")
	seen := make(map[string]bool)
	for _, m := range models {
		if !seen[m.PkgPath] {
			seen[m.PkgPath] = true
			alias := aliases[m.PkgPath]
			b.WriteString(fmt.Sprintf("\t%s %q\n", alias, m.PkgPath))
		}
	}
	b.WriteString(")\n\n")

	// DB struct
	b.WriteString("type DB struct {\n")
	b.WriteString("\t*drel.Engine\n")
	for _, m := range models {
		alias := aliases[m.PkgPath]
		fieldName := pluralize(m.Name)
		b.WriteString(fmt.Sprintf("\t%s *drel.Repository[%s.%s]\n", fieldName, alias, m.Name))
	}
	b.WriteString("}\n\n")

	// Open function
	b.WriteString("func Open(dsn string, opts ...drel.Option) (*DB, error) {\n")
	b.WriteString("\tengine, err := drel.NewEngine(dsn, opts...)\n")
	b.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
	b.WriteString("\treturn &DB{\n")
	b.WriteString("\t\tEngine: engine,\n")
	for _, m := range models {
		alias := aliases[m.PkgPath]
		fieldName := pluralize(m.Name)
		b.WriteString(fmt.Sprintf("\t\t%s: drel.NewRepository(engine, %s.%sMeta),\n", fieldName, alias, m.Name))
	}
	b.WriteString("\t}, nil\n")
	b.WriteString("}\n")

	// Emit RelationInfo and IncludeSpec vars for all relationships.
	for _, m := range models {
		alias := aliases[m.PkgPath]
		for _, f := range m.Fields {
			if f.Relation == nil {
				continue
			}
			drelType := relationType(f.Relation.Type)
			if drelType == "" {
				continue
			}
			target := f.Relation.TargetModel
			if target == "" {
				continue
			}

			// Find the target model's alias.
			targetAlias := ""
			for _, tm := range models {
				if tm.Name == target {
					targetAlias = aliases[tm.PkgPath]
					break
				}
			}
			if targetAlias == "" {
				continue
			}

			exportedField := exportName(f.Name)
			varName := m.Name + exportedField + "Rel"

			b.WriteString(fmt.Sprintf("\nvar %s = drel.RelationInfo{\n", varName))
			b.WriteString(fmt.Sprintf("\tName:        %q,\n", exportedField))
			b.WriteString(fmt.Sprintf("\tType:        %s,\n", drelType))
			b.WriteString(fmt.Sprintf("\tFKColumn:    %q,\n", f.Relation.FK))

			if f.Relation.Type == "many_to_many" {
				b.WriteString(fmt.Sprintf("\tJoinTable:   %q,\n", f.Relation.JoinTable))
				b.WriteString(fmt.Sprintf("\tRefColumn:   %q,\n", f.Relation.RefColumn))
			}

			b.WriteString(fmt.Sprintf("\tRelatedMeta: drel.ToMetaBase(&%s.%sMeta),\n", targetAlias, target))

			switch f.Relation.Type {
			case "has_many", "many_to_many":
				b.WriteString("\tFieldSetter: func(parent any, related any) {\n")
				b.WriteString(fmt.Sprintf("\t\tp := parent.(*%s.%s)\n", alias, m.Name))
				b.WriteString("\t\titems := related.([]any)\n")
				if isSliceOfPointers(f.GoType) {
					b.WriteString(fmt.Sprintf("\t\tresult := make([]*%s.%s, len(items))\n", targetAlias, target))
					b.WriteString("\t\tfor i, item := range items {\n")
					b.WriteString(fmt.Sprintf("\t\t\tresult[i] = item.(*%s.%s)\n", targetAlias, target))
					b.WriteString("\t\t}\n")
				} else {
					b.WriteString(fmt.Sprintf("\t\tresult := make([]%s.%s, len(items))\n", targetAlias, target))
					b.WriteString("\t\tfor i, item := range items {\n")
					b.WriteString(fmt.Sprintf("\t\t\tresult[i] = *item.(*%s.%s)\n", targetAlias, target))
					b.WriteString("\t\t}\n")
				}
				b.WriteString(fmt.Sprintf("\t\tp.%s = result\n", f.Name))
				b.WriteString("\t},\n")

			case "has_one", "belongs_to":
				b.WriteString("\tFieldSetter: func(parent any, related any) {\n")
				b.WriteString(fmt.Sprintf("\t\tp := parent.(*%s.%s)\n", alias, m.Name))
				b.WriteString(fmt.Sprintf("\t\tp.%s = related.(*%s.%s)\n", f.Name, targetAlias, target))
				b.WriteString("\t},\n")
			}

			b.WriteString("}\n")

			includeVarName := m.Name + "Include" + exportedField
			b.WriteString(fmt.Sprintf("\nvar %s = drel.NewIncludeSpec(&%s)\n", includeVarName, varName))
		}
	}

	return b.String()
}

// relationType maps rel tag type strings to the drel.RelationType constant names.
func relationType(relType string) string {
	switch relType {
	case "has_many":
		return "drel.HasMany"
	case "has_one":
		return "drel.HasOne"
	case "belongs_to":
		return "drel.BelongsTo"
	case "many_to_many":
		return "drel.ManyToMany"
	default:
		return ""
	}
}

// isSliceOfPointers returns true if the Go type string represents a slice of pointers (e.g. "[]*Post").
func isSliceOfPointers(goType string) bool {
	return strings.HasPrefix(goType, "[]*")
}

func resolveImportAliases(models []ModelInfo) map[string]string {
	aliases := make(map[string]string)
	aliasCount := make(map[string]int)

	for _, m := range models {
		if _, ok := aliases[m.PkgPath]; ok {
			continue
		}
		base := path.Base(m.PkgPath)
		aliasCount[base]++
		if aliasCount[base] == 1 {
			aliases[m.PkgPath] = base
		} else {
			aliases[m.PkgPath] = fmt.Sprintf("%s%d", base, aliasCount[base])
		}
	}
	return aliases
}
