package codegen

import (
	"go/parser"
	"go/token"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestEmitModelFile_SimpleModel(t *testing.T) {
	m := ModelInfo{
		Name:      "Product",
		PkgPath:   "testmod/models",
		PkgName:   "models",
		PKType:    "int",
		TableName: "products",
		Fields: []FieldInfo{
			{Name: "name", GoType: "string", ColumnName: "name", LocalGoType: "string"},
			{Name: "price", GoType: "int", ColumnName: "price", LocalGoType: "int"},
			{Name: "inStock", GoType: "bool", ColumnName: "in_stock", LocalGoType: "bool"},
		},
	}

	out := EmitModelFile(m)

	// Header
	assert.Contains(t, out, "// Code generated by drel. DO NOT EDIT.")
	assert.Contains(t, out, "package models")
	assert.Contains(t, out, `"github.com/alternayte/drel"`)

	// Column references struct
	assert.Contains(t, out, "var Products = struct {")
	assert.Contains(t, out, "ID drel.OrderedColumn[int]")
	assert.Contains(t, out, "Name drel.StringColumn")
	assert.Contains(t, out, "Price drel.OrderedColumn[int]")
	assert.Contains(t, out, "InStock drel.BoolColumn")
	assert.Contains(t, out, `Name: drel.NewStringCol("name")`)
	assert.Contains(t, out, `Price: drel.NewOrderedCol[int]("price")`)
	assert.Contains(t, out, `InStock: drel.NewBoolCol("in_stock")`)

	// Scan function
	assert.Contains(t, out, "func scanProduct(row drel.Row) (*Product, error)")
	assert.Contains(t, out, "idPtr, createdAtPtr, updatedAtPtr := p.ScanPtrs()")
	assert.Contains(t, out, "idPtr")
	assert.Contains(t, out, "&p.name")
	assert.Contains(t, out, "&p.price")
	assert.Contains(t, out, "&p.inStock")
	assert.Contains(t, out, "createdAtPtr")
	assert.Contains(t, out, "updatedAtPtr")

	// Snapshot
	assert.Contains(t, out, "type productSnapshot struct {")
	assert.Contains(t, out, "func snapshotProduct(p *Product) any")
	assert.Contains(t, out, "name: p.name")
	assert.Contains(t, out, "price: p.price")

	// Diff
	assert.Contains(t, out, "func diffProduct(p *Product, snap any) []drel.FieldChange")
	assert.Contains(t, out, `s := snap.(productSnapshot)`)
	assert.Contains(t, out, `Column: "name", Value: p.name`)

	// PK value
	assert.Contains(t, out, "func productPKValue(p *Product) any")
	assert.Contains(t, out, "return p.ID()")

	// Insert columns
	assert.Contains(t, out, "func productInsertColumns(p *Product) ([]string, []any)")
	assert.Contains(t, out, `"name", "price", "in_stock"`)
	assert.Contains(t, out, "p.name, p.price, p.inStock")

	// Scan returning
	assert.Contains(t, out, "func productScanReturning(p *Product, row drel.Row) error")
	assert.Contains(t, out, "idPtr, createdAtPtr, updatedAtPtr := p.ScanPtrs()")
	assert.Contains(t, out, "row.Scan(idPtr, createdAtPtr, updatedAtPtr)")

	// ModelMeta
	assert.Contains(t, out, "var ProductMeta = drel.ModelMeta[Product]{")
	assert.Contains(t, out, `Table:   "products"`)
	assert.Contains(t, out, `Columns: []string{"id", "name", "price", "in_stock", "created_at", "updated_at"}`)
	assert.Contains(t, out, `PKColumn: "id"`)
	assert.Contains(t, out, "Scan:          scanProduct,")
	assert.Contains(t, out, "Snapshot:      snapshotProduct,")
	assert.Contains(t, out, "Diff:          diffProduct,")
	assert.Contains(t, out, "PKValue:       productPKValue,")
	assert.Contains(t, out, "InsertColumns: productInsertColumns,")
	assert.Contains(t, out, "ScanReturning: productScanReturning,")
}

func TestEmitModelFile_WithSoftDelete(t *testing.T) {
	m := ModelInfo{
		Name:          "Article",
		PkgPath:       "testmod/models",
		PkgName:       "models",
		PKType:        "int",
		TableName:     "articles",
		HasSoftDelete: true,
		Fields: []FieldInfo{
			{Name: "title", GoType: "string", ColumnName: "title", LocalGoType: "string"},
		},
	}

	out := EmitModelFile(m)

	// Verify deletedAt in scan
	assert.Contains(t, out, "p.DeletedAtPtr()")

	// Verify deleted_at column in column refs
	assert.Contains(t, out, `DeletedAt drel.Column[*time.Time]`)
	assert.Contains(t, out, `DeletedAt: drel.NewCol[*time.Time]("deleted_at")`)

	// Verify deleted_at in Columns list
	assert.Contains(t, out, `"deleted_at"`)

	// Verify scan order: fields, then softDelete, then createdAt/updatedAt
	scanLine := extractLine(out, "row.Scan(")
	assert.True(t, strings.Index(scanLine, "DeletedAtPtr") < strings.Index(scanLine, "createdAtPtr"),
		"deletedAt should be scanned before createdAt")
}

func TestEmitModelFile_WithVersioned(t *testing.T) {
	m := ModelInfo{
		Name:         "Item",
		PkgPath:      "testmod/models",
		PkgName:      "models",
		PKType:       "int",
		TableName:    "items",
		HasVersioned: true,
		Fields: []FieldInfo{
			{Name: "label", GoType: "string", ColumnName: "label", LocalGoType: "string"},
		},
	}

	out := EmitModelFile(m)

	// Verify version in scan
	assert.Contains(t, out, "p.VersionPtr()")

	// Verify version column in column refs
	assert.Contains(t, out, "Version drel.OrderedColumn[int]")
	assert.Contains(t, out, `Version: drel.NewOrderedCol[int]("version")`)

	// Verify "version" in Columns list
	assert.Contains(t, out, `"version"`)

	// Verify scan order: fields, then version, then createdAt/updatedAt
	scanLine := extractLine(out, "row.Scan(")
	assert.True(t, strings.Index(scanLine, "VersionPtr") < strings.Index(scanLine, "createdAtPtr"),
		"version should be scanned before createdAt")
}

func TestColumnType(t *testing.T) {
	tests := []struct {
		goType   string
		wantType string
		wantCtor string
	}{
		{"int", "drel.OrderedColumn[int]", `drel.NewOrderedCol[int]("col")`},
		{"int64", "drel.OrderedColumn[int64]", `drel.NewOrderedCol[int64]("col")`},
		{"float64", "drel.OrderedColumn[float64]", `drel.NewOrderedCol[float64]("col")`},
		{"string", "drel.StringColumn", `drel.NewStringCol("col")`},
		{"bool", "drel.BoolColumn", `drel.NewBoolCol("col")`},
		{"time.Time", "drel.Column[time.Time]", `drel.NewCol[time.Time]("col")`},
	}
	for _, tt := range tests {
		t.Run(tt.goType, func(t *testing.T) {
			assert.Equal(t, tt.wantType, columnTypeName(tt.goType))
			assert.Equal(t, tt.wantCtor, columnConstructor(tt.goType, "col"))
		})
	}
}

func TestExportName(t *testing.T) {
	tests := []struct{ input, want string }{
		{"name", "Name"},
		{"inStock", "InStock"},
		{"id", "Id"},
		{"", ""},
	}
	for _, tt := range tests {
		t.Run(tt.input, func(t *testing.T) {
			assert.Equal(t, tt.want, exportName(tt.input))
		})
	}
}

func TestEmitDBFile(t *testing.T) {
	models := []ModelInfo{
		{
			Name:      "User",
			PkgPath:   "myapp/features/users",
			PkgName:   "users",
			PKType:    "int",
			TableName: "users",
			Fields: []FieldInfo{
				{Name: "name", GoType: "string", ColumnName: "name", LocalGoType: "string"},
			},
		},
		{
			Name:      "Post",
			PkgPath:   "myapp/features/posts",
			PkgName:   "posts",
			PKType:    "int",
			TableName: "posts",
			Fields: []FieldInfo{
				{Name: "title", GoType: "string", ColumnName: "title", LocalGoType: "string"},
			},
		},
	}

	out := EmitDBFile(models, "db")

	// Header
	assert.Contains(t, out, "// Code generated by drel. DO NOT EDIT.")
	assert.Contains(t, out, "package db")

	// Imports
	assert.Contains(t, out, `"github.com/alternayte/drel"`)
	assert.Contains(t, out, `users "myapp/features/users"`)
	assert.Contains(t, out, `posts "myapp/features/posts"`)

	// DB struct
	assert.Contains(t, out, "type DB struct {")
	assert.Contains(t, out, "*drel.Engine")
	assert.Contains(t, out, "Users *users.UserRepository")
	assert.Contains(t, out, "Posts *posts.PostRepository")

	// Open function
	assert.Contains(t, out, "func Open(dsn string, opts ...drel.Option) (*DB, error)")
	assert.Contains(t, out, "drel.NewEngine(dsn, opts...)")
	assert.Contains(t, out, "&users.UserRepository{Repository: drel.NewRepository(engine, users.UserMeta)}")
	assert.Contains(t, out, "&posts.PostRepository{Repository: drel.NewRepository(engine, posts.PostMeta)}")
}

func TestEmitDBFile_DedupImports(t *testing.T) {
	// Two models from the same package should only produce one import.
	models := []ModelInfo{
		{Name: "User", PkgPath: "myapp/models", PkgName: "models", PKType: "int", TableName: "users"},
		{Name: "Post", PkgPath: "myapp/models", PkgName: "models", PKType: "int", TableName: "posts"},
	}

	out := EmitDBFile(models, "db")

	// The import should appear exactly once.
	assert.Equal(t, 1, strings.Count(out, `models "myapp/models"`))
}

func TestEmitModelFile_WithSingleColVO(t *testing.T) {
	m := ModelInfo{
		Name:      "User",
		PkgName:   "models",
		PKType:    "int",
		TableName: "users",
		Fields: []FieldInfo{
			{Name: "name", GoType: "string", ColumnName: "name", LocalGoType: "string"},
			{Name: "email", GoType: "testmod/models.Email", ColumnName: "email", IsVO: true, LocalGoType: "Email"},
		},
	}

	output := EmitModelFile(m)

	assert.Contains(t, output, "drel.Column[Email]")
	assert.Contains(t, output, `drel.NewCol[Email]("email")`)
	assert.Contains(t, output, "email Email")        // snapshot struct field
	assert.Contains(t, output, "&p.email")           // scan
	assert.Contains(t, output, "p.email != s.email") // diff
}

func TestEmitModelFile_MultiColVOColumnRefs(t *testing.T) {
	m := ModelInfo{
		Name:      "Account",
		PkgName:   "models",
		PKType:    "int",
		TableName: "accounts",
		Fields: []FieldInfo{
			{Name: "name", GoType: "string", ColumnName: "name", LocalGoType: "string"},
			{
				Name:          "balance",
				GoType:        "testmod/models.Money",
				ColumnName:    "balance_amount",
				LocalGoType:   "Money",
				IsMultiColVO:  true,
				MultiColNames: []string{"balance_amount", "balance_currency"},
				MultiColTypes: []string{"text", "text"},
			},
		},
	}

	out := EmitModelFile(m)

	// One typed column field per sub-column, named <Field><SubColExport>.
	assert.Contains(t, out, "BalanceAmount drel.Column[any]")
	assert.Contains(t, out, "BalanceCurrency drel.Column[any]")
	assert.Contains(t, out, `BalanceAmount: drel.NewCol[any]("balance_amount")`)
	assert.Contains(t, out, `BalanceCurrency: drel.NewCol[any]("balance_currency")`)
	// The VO field itself must NOT produce a drel.Column[Money] ref.
	assert.NotContains(t, out, "drel.Column[Money]")
}

func TestEmitModelFile_MultiColVOScanDiffValue(t *testing.T) {
	m := ModelInfo{
		Name:      "Account",
		PkgName:   "models",
		PKType:    "int",
		TableName: "accounts",
		Fields: []FieldInfo{
			{Name: "name", GoType: "string", ColumnName: "name", LocalGoType: "string"},
			{
				Name:          "balance",
				GoType:        "testmod/models.Money",
				ColumnName:    "balance_amount",
				LocalGoType:   "Money",
				IsMultiColVO:  true,
				MultiColNames: []string{"balance_amount", "balance_currency"},
				MultiColTypes: []string{"text", "text"},
			},
		},
	}

	out := EmitModelFile(m)

	// Columns meta lists both sub-columns in order, between id and created_at.
	assert.Contains(t, out, `Columns: []string{"id", "name", "balance_amount", "balance_currency", "created_at", "updated_at"}`)

	// Generated DrelValues helper.
	assert.Contains(t, out, "func accountMultiVals(v Money) []any {")
	assert.Contains(t, out, "vals, err := v.DrelValues()")
	assert.Contains(t, out, "panic(")

	// Scan: temporaries + DrelScanMulti reconstruction.
	assert.Contains(t, out, "var balanceVals = make([]any, 2)")
	assert.Contains(t, out, "&balanceVals[0]")
	assert.Contains(t, out, "&balanceVals[1]")
	assert.Contains(t, out, "if err := p.balance.DrelScanMulti(balanceVals); err != nil {")

	// ColumnValue: positional case per sub-column, pulling from DrelValues.
	assert.Contains(t, out, "return accountMultiVals(p.balance)[0]")
	assert.Contains(t, out, "return accountMultiVals(p.balance)[1]")

	// InsertColumns: both sub-column names + both values, expanded inline.
	assert.Contains(t, out, `"balance_amount", "balance_currency"`)
	assert.Contains(t, out, "accountMultiVals(p.balance)[0], accountMultiVals(p.balance)[1]")
}

func TestEmitModelFile_MultiColVOSnapshotDiff(t *testing.T) {
	m := ModelInfo{
		Name:      "Account",
		PkgName:   "models",
		PKType:    "int",
		TableName: "accounts",
		Fields: []FieldInfo{
			{Name: "name", GoType: "string", ColumnName: "name", LocalGoType: "string"},
			{
				Name:          "balance",
				GoType:        "testmod/models.Money",
				ColumnName:    "balance_amount",
				LocalGoType:   "Money",
				IsMultiColVO:  true,
				MultiColNames: []string{"balance_amount", "balance_currency"},
				MultiColTypes: []string{"text", "text"},
			},
		},
	}

	out := EmitModelFile(m)

	// Snapshot struct: one []any field per multi-col VO, named <field>Vals.
	assert.Contains(t, out, "balanceVals []any")
	// Snapshot func captures DrelValues output.
	assert.Contains(t, out, "balanceVals: accountMultiVals(p.balance)")

	// Diff: one FieldChange per changed sub-column, compared element-wise.
	assert.Contains(t, out, "cur := accountMultiVals(p.balance)")
	assert.Contains(t, out, "if cur[0] != s.balanceVals[0] {")
	assert.Contains(t, out, `drel.FieldChange{Column: "balance_amount", Value: cur[0]}`)
	assert.Contains(t, out, "if cur[1] != s.balanceVals[1] {")
	assert.Contains(t, out, `drel.FieldChange{Column: "balance_currency", Value: cur[1]}`)
}

func TestEmitModelFile_MultiColVOCheckedSucceeds(t *testing.T) {
	m := ModelInfo{
		Name:      "Account",
		PkgName:   "models",
		PKType:    "int",
		TableName: "accounts",
		Fields: []FieldInfo{
			{Name: "name", GoType: "string", ColumnName: "name", LocalGoType: "string"},
			{
				Name:          "balance",
				GoType:        "testmod/models.Money",
				ColumnName:    "balance_amount",
				LocalGoType:   "Money",
				IsMultiColVO:  true,
				MultiColNames: []string{"balance_amount", "balance_currency"},
				MultiColTypes: []string{"text", "text"},
			},
		},
	}

	out, err := EmitModelFileChecked(m)
	require.NoError(t, err)
	assert.Contains(t, out, "func accountMultiVals(v Money) []any {")

	// The emitted source must be syntactically valid Go.
	_, perr := parser.ParseFile(token.NewFileSet(), "account_drel.go", out, parser.AllErrors)
	require.NoError(t, perr)
}

func TestEmitModelFile_SoftDeleteMeta(t *testing.T) {
	m := ModelInfo{
		Name: "Article", PkgName: "models", PKType: "int", TableName: "articles",
		HasSoftDelete: true,
		Fields: []FieldInfo{
			{Name: "title", GoType: "string", ColumnName: "title", LocalGoType: "string"},
		},
	}
	out := EmitModelFile(m)

	assert.Contains(t, out, "HasSoftDelete: true,")
	assert.Contains(t, out, "Filters: []drel.NamedFilter{drel.SoftDeleteFilter},")
}

func TestEmitModelFile_VersionedMeta(t *testing.T) {
	m := ModelInfo{
		Name: "Article", PkgName: "models", PKType: "int", TableName: "articles",
		HasVersioned: true,
		Fields: []FieldInfo{
			{Name: "title", GoType: "string", ColumnName: "title", LocalGoType: "string"},
		},
	}
	out := EmitModelFile(m)

	assert.Contains(t, out, "HasVersioned: true,")
	assert.Contains(t, out, "VersionValue:")
	assert.Contains(t, out, "p.Version()")
	assert.Contains(t, out, "SetVersion:")
	assert.Contains(t, out, "*p.VersionPtr() = v")
}

func TestEmitModelFile_AuditMeta(t *testing.T) {
	m := ModelInfo{
		Name: "Article", PkgName: "models", PKType: "int", TableName: "articles",
		HasAudit: true,
		Fields: []FieldInfo{
			{Name: "title", GoType: "string", ColumnName: "title", LocalGoType: "string"},
		},
	}
	out := EmitModelFile(m)

	assert.Contains(t, out, "HasAudit: true,")
	assert.Contains(t, out, "AuditSetCreate:")
	assert.Contains(t, out, "AuditPtrs()")
	assert.Contains(t, out, "AuditSetUpdate:")
}

func TestEmitModelFile_NoRelationsInPerModelFile(t *testing.T) {
	m := ModelInfo{
		Name:      "User",
		PkgName:   "models",
		PKType:    "int",
		TableName: "users",
		Fields: []FieldInfo{
			{Name: "name", GoType: "string", ColumnName: "name", LocalGoType: "string"},
			{Name: "posts", GoType: "[]*models.Post", Relation: &RelationFieldInfo{
				Type: "has_many", FK: "user_id", TargetModel: "Post",
			}},
		},
	}

	out := EmitModelFile(m)
	assert.NotContains(t, out, "RelationInfo")
	assert.NotContains(t, out, "IncludeSpec")
}

func TestEmitModelFile_TypedRepository(t *testing.T) {
	m := ModelInfo{
		Name:      "User",
		PkgName:   "models",
		PKType:    "int",
		TableName: "users",
		Fields: []FieldInfo{
			{Name: "name", GoType: "string", ColumnName: "name", LocalGoType: "string"},
		},
	}

	out := EmitModelFile(m)

	assert.Contains(t, out, "type UserRepository struct {")
	assert.Contains(t, out, "*drel.Repository[User]")
	assert.Contains(t, out, "func (r *UserRepository) FindByID(ctx context.Context, id int) (*User, error) {")
	assert.Contains(t, out, "return r.Find(ctx, id)")

	assert.Contains(t, out, "type TxUserRepository struct {")
	assert.Contains(t, out, "*drel.TxRepository[User]")
	assert.Contains(t, out, "func (r *TxUserRepository) FindByID(ctx context.Context, id int) (*User, error) {")
}

func TestEmitModelFile_TypedRepository_UUIDKey(t *testing.T) {
	m := ModelInfo{
		Name:      "Account",
		PkgName:   "models",
		PKType:    "uuid.UUID",
		PKTypePkg: "github.com/google/uuid",
		TableName: "accounts",
		Fields: []FieldInfo{
			{Name: "name", GoType: "string", ColumnName: "name", LocalGoType: "string"},
		},
	}

	out := EmitModelFile(m)

	assert.Contains(t, out, "func (r *AccountRepository) FindByID(ctx context.Context, id uuid.UUID) (*Account, error) {")
}

func TestEmitModelFile_IntPK_AutoIncrement(t *testing.T) {
	m := ModelInfo{
		Name: "Tag", PkgName: "models", PKType: "int", TableName: "tags",
		Fields: []FieldInfo{{Name: "Name", GoType: "string", ColumnName: "name", LocalGoType: "string"}},
	}
	out := EmitModelFile(m)
	if strings.Contains(out, "KeyStrategy") {
		t.Fatal("int PK must not emit a KeyStrategy (defaults to auto-increment)")
	}
	if strings.Contains(out, "tagScanGenerated") {
		t.Fatal("int PK must not emit ScanGenerated")
	}
}

func TestEmitModelFile_UUIDPK_AppAssigned(t *testing.T) {
	m := ModelInfo{
		Name: "Account", PkgName: "models",
		PKType: "uuid.UUID", PKTypePkg: "github.com/google/uuid",
		TableName: "accounts",
		Fields:    []FieldInfo{{Name: "Name", GoType: "string", ColumnName: "name", LocalGoType: "string"}},
	}
	out := EmitModelFile(m)
	for _, want := range []string{
		"KeyStrategy: drel.KeyAppAssigned,",
		"GenerateKey: drel.UUIDv7Key,",
		"p.SetID(key.(uuid.UUID))",
		"func accountKeyIsZero(p *Account) bool {",
		"func accountScanGenerated(p *Account, row drel.Row) error {",
		"ScanGenerated: accountScanGenerated,",
		"KeyIsZero:",
	} {
		if !strings.Contains(out, want) {
			t.Fatalf("missing %q in:\n%s", want, out)
		}
	}
}

func TestEmitModelFile_VODiffUsesEqual(t *testing.T) {
	m := ModelInfo{
		Name: "Account", PkgName: "models", PKType: "int", TableName: "accounts",
		Fields: []FieldInfo{
			{Name: "email", GoType: "testmod/models.Email", ColumnName: "email", LocalGoType: "Email", IsVO: true, IsComparable: true},
			{Name: "tags", GoType: "testmod/models.Tags", ColumnName: "tags", LocalGoType: "Tags", IsVO: true, HasEqual: true, IsComparable: false},
		},
	}
	out := EmitModelFile(m)
	// Comparable VO with no Equal keeps !=.
	assert.Contains(t, out, "p.email != s.email")
	// VO with Equal uses the method, negated.
	assert.Contains(t, out, "!p.tags.Equal(s.tags)")
	assert.NotContains(t, out, "p.tags != s.tags")
}

func TestEmitModelFileChecked_NonComparableVONoEqualErrors(t *testing.T) {
	m := ModelInfo{
		Name: "Account", PkgName: "models", PKType: "int", TableName: "accounts",
		Fields: []FieldInfo{
			{Name: "tags", GoType: "testmod/models.Tags", ColumnName: "tags", LocalGoType: "Tags", IsVO: true, HasEqual: false, IsComparable: false},
		},
	}
	_, err := EmitModelFileChecked(m)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "Account")
	assert.Contains(t, err.Error(), "tags")
	assert.Contains(t, err.Error(), "Equal")
}

// extractLine returns the first line in s that contains substr.
func extractLine(s, substr string) string {
	for _, line := range strings.Split(s, "\n") {
		if strings.Contains(line, substr) {
			return line
		}
	}
	return ""
}
