package codegen

import (
	"fmt"
	"strings"
	"unicode"
)

// exportName capitalises the first letter of a name.
func exportName(name string) string {
	if name == "" {
		return name
	}
	rs := []rune(name)
	rs[0] = unicode.ToUpper(rs[0])
	return string(rs)
}

// columnTypeName returns the drel column type for a Go type.
func columnTypeName(goType string) string {
	switch goType {
	case "string":
		return "drel.StringColumn"
	case "bool":
		return "drel.BoolColumn"
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64",
		"float32", "float64":
		return fmt.Sprintf("drel.OrderedColumn[%s]", goType)
	default:
		return fmt.Sprintf("drel.Column[%s]", goType)
	}
}

// columnConstructor returns the drel constructor call for a Go type and column name.
func columnConstructor(goType, colName string) string {
	switch goType {
	case "string":
		return fmt.Sprintf("drel.NewStringCol(%q)", colName)
	case "bool":
		return fmt.Sprintf("drel.NewBoolCol(%q)", colName)
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64",
		"float32", "float64":
		return fmt.Sprintf("drel.NewOrderedCol[%s](%q)", goType, colName)
	default:
		return fmt.Sprintf("drel.NewCol[%s](%q)", goType, colName)
	}
}

// EmitModelFile generates the complete per-model _drel.go file content.
func EmitModelFile(m ModelInfo) string {
	var b strings.Builder
	lower := strings.ToLower(m.Name)
	varPlural := pluralize(m.Name)

	// Header
	b.WriteString("// Code generated by drel. DO NOT EDIT.\n\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", m.PkgName))
	b.WriteString("import (\n\t\"time\"\n\n\t\"github.com/alternayte/drel\"\n)\n\n")

	// --- Column references ---
	emitColumnRefs(&b, m, varPlural)

	// --- All columns list ---
	allCols := allColumns(m)

	// --- Scan function ---
	emitScanFunc(&b, m, lower, allCols)

	// --- Snapshot struct + function ---
	emitSnapshot(&b, m, lower)

	// --- Diff function ---
	emitDiff(&b, m, lower)

	// --- PK value ---
	b.WriteString(fmt.Sprintf("func %sPKValue(p *%s) any {\n\treturn p.id\n}\n\n", lower, m.Name))

	// --- Insert columns ---
	emitInsertColumns(&b, m, lower)

	// --- Scan returning ---
	emitScanReturning(&b, m, lower)

	// --- ModelMeta ---
	emitMeta(&b, m, lower, varPlural, allCols)

	return b.String()
}

func emitColumnRefs(b *strings.Builder, m ModelInfo, varPlural string) {
	// Struct type definition
	b.WriteString(fmt.Sprintf("var %s = struct {\n", varPlural))
	// ID column - always present, derived from PKType
	b.WriteString(fmt.Sprintf("\tID %s\n", columnTypeName(m.PKType)))
	for _, f := range m.Fields {
		b.WriteString(fmt.Sprintf("\t%s %s\n", exportName(f.Name), columnTypeName(f.GoType)))
	}
	if m.HasSoftDelete {
		b.WriteString("\tDeletedAt drel.Column[*time.Time]\n")
	}
	if m.HasVersioned {
		b.WriteString("\tVersion drel.OrderedColumn[int]\n")
	}
	b.WriteString("\tCreatedAt drel.OrderedColumn[time.Time]\n")
	b.WriteString("\tUpdatedAt drel.OrderedColumn[time.Time]\n")
	b.WriteString("}{\n")

	// Struct literal values
	b.WriteString(fmt.Sprintf("\tID: %s,\n", columnConstructor(m.PKType, "id")))
	for _, f := range m.Fields {
		b.WriteString(fmt.Sprintf("\t%s: %s,\n", exportName(f.Name), columnConstructor(f.GoType, f.ColumnName)))
	}
	if m.HasSoftDelete {
		b.WriteString("\tDeletedAt: drel.NewCol[*time.Time](\"deleted_at\"),\n")
	}
	if m.HasVersioned {
		b.WriteString("\tVersion: drel.NewOrderedCol[int](\"version\"),\n")
	}
	b.WriteString("\tCreatedAt: drel.NewOrderedCol[time.Time](\"created_at\"),\n")
	b.WriteString("\tUpdatedAt: drel.NewOrderedCol[time.Time](\"updated_at\"),\n")
	b.WriteString("}\n\n")
}

// allColumns returns the full ordered list of column names for this model.
func allColumns(m ModelInfo) []string {
	cols := []string{"id"}
	for _, f := range m.Fields {
		cols = append(cols, f.ColumnName)
	}
	if m.HasSoftDelete {
		cols = append(cols, "deleted_at")
	}
	if m.HasVersioned {
		cols = append(cols, "version")
	}
	cols = append(cols, "created_at", "updated_at")
	return cols
}

func emitScanFunc(b *strings.Builder, m ModelInfo, lower string, allCols []string) {
	b.WriteString(fmt.Sprintf("func scan%s(row drel.Row) (*%s, error) {\n", exportName(lower), m.Name))
	b.WriteString(fmt.Sprintf("\tp := &%s{}\n", m.Name))

	// Build scan args
	var scanArgs []string
	scanArgs = append(scanArgs, "&p.id")
	for _, f := range m.Fields {
		scanArgs = append(scanArgs, fmt.Sprintf("&p.%s", f.Name))
	}
	if m.HasSoftDelete {
		scanArgs = append(scanArgs, "&p.deletedAt")
	}
	if m.HasVersioned {
		scanArgs = append(scanArgs, "&p.version")
	}
	scanArgs = append(scanArgs, "&p.createdAt", "&p.updatedAt")

	b.WriteString(fmt.Sprintf("\terr := row.Scan(%s)\n", strings.Join(scanArgs, ", ")))
	b.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
	b.WriteString("\treturn p, nil\n}\n\n")
}

func emitSnapshot(b *strings.Builder, m ModelInfo, lower string) {
	// Snapshot struct
	b.WriteString(fmt.Sprintf("type %sSnapshot struct {\n", lower))
	for _, f := range m.Fields {
		b.WriteString(fmt.Sprintf("\t%s %s\n", f.Name, f.GoType))
	}
	b.WriteString("}\n\n")

	// Snapshot function
	b.WriteString(fmt.Sprintf("func snapshot%s(p *%s) any {\n", exportName(lower), m.Name))
	b.WriteString(fmt.Sprintf("\treturn %sSnapshot{", lower))
	for i, f := range m.Fields {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(fmt.Sprintf("%s: p.%s", f.Name, f.Name))
	}
	b.WriteString("}\n}\n\n")
}

func emitDiff(b *strings.Builder, m ModelInfo, lower string) {
	b.WriteString(fmt.Sprintf("func diff%s(p *%s, snap any) []drel.FieldChange {\n", exportName(lower), m.Name))
	b.WriteString(fmt.Sprintf("\ts := snap.(%sSnapshot)\n", lower))
	b.WriteString("\tvar changes []drel.FieldChange\n")
	for _, f := range m.Fields {
		b.WriteString(fmt.Sprintf("\tif p.%s != s.%s {\n", f.Name, f.Name))
		b.WriteString(fmt.Sprintf("\t\tchanges = append(changes, drel.FieldChange{Column: %q, Value: p.%s})\n", f.ColumnName, f.Name))
		b.WriteString("\t}\n")
	}
	b.WriteString("\treturn changes\n}\n\n")
}

func emitInsertColumns(b *strings.Builder, m ModelInfo, lower string) {
	b.WriteString(fmt.Sprintf("func %sInsertColumns(p *%s) ([]string, []any) {\n", lower, m.Name))
	var colNames []string
	var colVals []string
	for _, f := range m.Fields {
		colNames = append(colNames, fmt.Sprintf("%q", f.ColumnName))
		colVals = append(colVals, fmt.Sprintf("p.%s", f.Name))
	}
	b.WriteString(fmt.Sprintf("\treturn []string{%s}, []any{%s}\n", strings.Join(colNames, ", "), strings.Join(colVals, ", ")))
	b.WriteString("}\n\n")
}

func emitScanReturning(b *strings.Builder, m ModelInfo, lower string) {
	b.WriteString(fmt.Sprintf("func %sScanReturning(p *%s, row drel.Row) error {\n", lower, m.Name))
	scanArgs := []string{"&p.id", "&p.createdAt", "&p.updatedAt"}
	b.WriteString(fmt.Sprintf("\treturn row.Scan(%s)\n", strings.Join(scanArgs, ", ")))
	b.WriteString("}\n\n")
}

func emitMeta(b *strings.Builder, m ModelInfo, lower, varPlural string, allCols []string) {
	b.WriteString(fmt.Sprintf("var %sMeta = drel.ModelMeta[%s]{\n", m.Name, m.Name))
	b.WriteString(fmt.Sprintf("\tTable:   %q,\n", m.TableName))

	// Columns
	quoted := make([]string, len(allCols))
	for i, c := range allCols {
		quoted[i] = fmt.Sprintf("%q", c)
	}
	b.WriteString(fmt.Sprintf("\tColumns: []string{%s},\n", strings.Join(quoted, ", ")))
	b.WriteString("\tPKColumn: \"id\",\n")
	b.WriteString(fmt.Sprintf("\tScan:          scan%s,\n", exportName(lower)))
	b.WriteString(fmt.Sprintf("\tSnapshot:      snapshot%s,\n", exportName(lower)))
	b.WriteString(fmt.Sprintf("\tDiff:          diff%s,\n", exportName(lower)))
	b.WriteString(fmt.Sprintf("\tPKValue:       %sPKValue,\n", lower))
	b.WriteString(fmt.Sprintf("\tInsertColumns: %sInsertColumns,\n", lower))
	b.WriteString(fmt.Sprintf("\tScanReturning: %sScanReturning,\n", lower))
	b.WriteString("}\n")
}
