// Code generated by drel. DO NOT EDIT.

package db

import (
	"github.com/alternayte/drel"
	models "github.com/alternayte/drel/examples/sqlite-todo/models"
)

type DB struct {
	*drel.Engine
	Notes *models.NoteRepository
}

func Open(dsn string, opts ...drel.Option) (*DB, error) {
	engine, err := drel.NewEngine(dsn, opts...)
	if err != nil {
		return nil, err
	}
	return &DB{
		Engine: engine,
		Notes:  &models.NoteRepository{Repository: drel.NewRepository(engine, models.NoteMeta)},
	}, nil
}
