// Example: enums
//
// Demonstrates integer enums and string enums with IsValid/Values helpers
// generated by drel codegen. Shows that enum validation works at the Go
// level before a DB round-trip.
//
// Usage:
//
//	cd examples/enums
//	go run ../../cmd/drel generate   # generates models/account_drel.go + db/drel_gen.go
//	go run .
package main

import (
	"fmt"

	"github.com/alternayte/drel/examples/enums/models"
)

func main() {
	fmt.Println(models.RoleAdmin.IsValid())    // true
	fmt.Println(models.Role("bogus").IsValid()) // false
	fmt.Println(models.RoleValues())
	fmt.Println(models.PriorityHigh.IsValid()) // true
	fmt.Println(models.PriorityValues())
}
