// Code generated by drel. DO NOT EDIT.

package db

import (
	"github.com/alternayte/drel"
	models "github.com/alternayte/drel/examples/relationships/models"
)

type DB struct {
	*drel.Engine
	Authors *drel.Repository[models.Author]
	AuthorProfiles *drel.Repository[models.AuthorProfile]
	Books *drel.Repository[models.Book]
}

func Open(dsn string, opts ...drel.Option) (*DB, error) {
	engine, err := drel.NewEngine(dsn, opts...)
	if err != nil {
		return nil, err
	}
	return &DB{
		Engine: engine,
		Authors: drel.NewRepository(engine, models.AuthorMeta),
		AuthorProfiles: drel.NewRepository(engine, models.AuthorProfileMeta),
		Books: drel.NewRepository(engine, models.BookMeta),
	}, nil
}
