// Code generated by drel. DO NOT EDIT.

package accounts

import (
	"context"
	"fmt"

	"github.com/alternayte/drel"
)

var Accounts = struct {
	ID              drel.OrderedColumn[int]
	Owner           drel.StringColumn
	BalanceAmount   drel.Column[any]
	BalanceCurrency drel.Column[any]
	CreatedAt       drel.TimeColumn
	UpdatedAt       drel.TimeColumn
}{
	ID:              drel.NewOrderedCol[int]("id"),
	Owner:           drel.NewStringCol("owner"),
	BalanceAmount:   drel.NewCol[any]("balance_amount"),
	BalanceCurrency: drel.NewCol[any]("balance_currency"),
	CreatedAt:       drel.NewTimeCol("created_at"),
	UpdatedAt:       drel.NewTimeCol("updated_at"),
}

func accountMultiVals(v Money) []any {
	vals, err := v.DrelValues()
	if err != nil {
		panic(fmt.Sprintf("drel: Account multi-column VO DrelValues: %v", err))
	}
	return vals
}

func scanAccount(row drel.Row) (*Account, error) {
	p := &Account{}
	idPtr, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	var balanceVals = make([]any, 2)
	err := row.Scan(idPtr, &p.owner, &balanceVals[0], &balanceVals[1], createdAtPtr, updatedAtPtr)
	if err != nil {
		return nil, err
	}
	if err := p.balance.DrelScanMulti(balanceVals); err != nil {
		return nil, err
	}
	return p, nil
}

type accountSnapshot struct {
	owner       string
	balanceVals []any
}

func snapshotAccount(p *Account) any {
	return accountSnapshot{owner: p.owner, balanceVals: accountMultiVals(p.balance)}
}

func diffAccount(p *Account, snap any) []drel.FieldChange {
	s := snap.(accountSnapshot)
	var changes []drel.FieldChange
	if p.owner != s.owner {
		changes = append(changes, drel.FieldChange{Column: "owner", Value: p.owner})
	}
	{
		cur := accountMultiVals(p.balance)
		if cur[0] != s.balanceVals[0] {
			changes = append(changes, drel.FieldChange{Column: "balance_amount", Value: cur[0]})
		}
		if cur[1] != s.balanceVals[1] {
			changes = append(changes, drel.FieldChange{Column: "balance_currency", Value: cur[1]})
		}
	}
	return changes
}

func accountPKValue(p *Account) any {
	return p.ID()
}

func accountColumnValue(p *Account, idx int) any {
	switch idx {
	case 0:
		return p.ID()
	case 1:
		return p.owner
	case 2:
		return accountMultiVals(p.balance)[0]
	case 3:
		return accountMultiVals(p.balance)[1]
	case 4:
		return p.CreatedAt()
	case 5:
		return p.UpdatedAt()
	}
	return nil
}

func accountInsertColumns(p *Account) ([]string, []any) {
	return []string{"owner", "balance_amount", "balance_currency"}, []any{p.owner, accountMultiVals(p.balance)[0], accountMultiVals(p.balance)[1]}
}

func accountScanReturning(p *Account, row drel.Row) error {
	idPtr, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	return row.Scan(idPtr, createdAtPtr, updatedAtPtr)
}

func accountNormalizeKey(v any) any {
	return drel.NormalizeIntKey(v)
}

var AccountMeta = drel.ModelMeta[Account]{
	Table:         "accounts",
	Columns:       []string{"id", "owner", "balance_amount", "balance_currency", "created_at", "updated_at"},
	PKColumn:      "id",
	Scan:          scanAccount,
	Snapshot:      snapshotAccount,
	Diff:          diffAccount,
	PKValue:       accountPKValue,
	InsertColumns: accountInsertColumns,
	ScanReturning: accountScanReturning,
	ColumnValue:   accountColumnValue,
	NormalizeKey:  accountNormalizeKey,
}

type AccountRepository struct {
	*drel.Repository[Account]
}

func (r *AccountRepository) FindByID(ctx context.Context, id int) (*Account, error) {
	return r.Find(ctx, id)
}

type TxAccountRepository struct {
	*drel.TxRepository[Account]
}

func (r *TxAccountRepository) FindByID(ctx context.Context, id int) (*Account, error) {
	return r.Find(ctx, id)
}

type UoWAccountRepository struct {
	*drel.UoWRepository[Account]
}

func (r *UoWAccountRepository) FindByID(ctx context.Context, id int) (*Account, error) {
	return r.Find(ctx, id)
}
