// Code generated by drel. DO NOT EDIT.

package db

import (
	"github.com/alternayte/drel"
	users "github.com/alternayte/drel/examples/multi-model/users"
)

type DB struct {
	*drel.Engine
	Users *users.UserRepository
}

func Open(dsn string, opts ...drel.Option) (*DB, error) {
	engine, err := drel.NewEngine(dsn, opts...)
	if err != nil {
		return nil, err
	}
	return &DB{
		Engine: engine,
		Users:  &users.UserRepository{Repository: drel.NewRepository(engine, users.UserMeta)},
	}, nil
}

// UnitOfWork is a change-tracking work session with typed, tracked
// repositories. Load through uow.<Model>, stage with Add/Remove, then
// SaveChanges to flush everything in a single transaction.
type UnitOfWork struct {
	*drel.UnitOfWork
	Users *users.UoWUserRepository
}

// NewUnitOfWork starts a new change-tracking work session.
func (db *DB) NewUnitOfWork() *UnitOfWork {
	uow := db.Engine.NewUnitOfWork()
	return &UnitOfWork{
		UnitOfWork: uow,
		Users:      &users.UoWUserRepository{UoWRepository: drel.NewUoWRepository(uow, users.UserMeta)},
	}
}
