// Code generated by drel. DO NOT EDIT.

package db

import (
	"github.com/alternayte/drel"
	users "github.com/alternayte/drel/examples/multi-model/users"
)

type DB struct {
	*drel.Engine
	Users *users.UserRepository
}

func Open(dsn string, opts ...drel.Option) (*DB, error) {
	engine, err := drel.NewEngine(dsn, opts...)
	if err != nil {
		return nil, err
	}
	return &DB{
		Engine: engine,
		Users:  &users.UserRepository{Repository: drel.NewRepository(engine, users.UserMeta)},
	}, nil
}
