// Code generated by drel. DO NOT EDIT.

package db

import (
	"github.com/alternayte/drel"
	products "github.com/alternayte/drel/examples/api/products"
)

type DB struct {
	*drel.Engine
	Products *products.ProductRepository
}

func Open(dsn string, opts ...drel.Option) (*DB, error) {
	engine, err := drel.NewEngine(dsn, opts...)
	if err != nil {
		return nil, err
	}
	return &DB{
		Engine: engine,
		Products: &products.ProductRepository{Repository: drel.NewRepository(engine, products.ProductMeta)},
	}, nil
}
