// Code generated by drel. DO NOT EDIT.

package orders

import (
	"context"
	"time"

	"github.com/alternayte/drel"
	uuid "github.com/google/uuid"
)

var Orders = struct {
	ID        drel.Column[uuid.UUID]
	Customer  drel.StringColumn
	Total     drel.OrderedColumn[int]
	CreatedAt drel.Column[time.Time]
	UpdatedAt drel.Column[time.Time]
}{
	ID:        drel.NewCol[uuid.UUID]("id"),
	Customer:  drel.NewStringCol("customer"),
	Total:     drel.NewOrderedCol[int]("total"),
	CreatedAt: drel.NewCol[time.Time]("created_at"),
	UpdatedAt: drel.NewCol[time.Time]("updated_at"),
}

func scanOrder(row drel.Row) (*Order, error) {
	p := &Order{}
	idPtr, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	err := row.Scan(idPtr, &p.Customer, &p.Total, createdAtPtr, updatedAtPtr)
	if err != nil {
		return nil, err
	}
	return p, nil
}

type orderSnapshot struct {
	Customer string
	Total    int
}

func snapshotOrder(p *Order) any {
	return orderSnapshot{Customer: p.Customer, Total: p.Total}
}

func diffOrder(p *Order, snap any) []drel.FieldChange {
	s := snap.(orderSnapshot)
	var changes []drel.FieldChange
	if p.Customer != s.Customer {
		changes = append(changes, drel.FieldChange{Column: "customer", Value: p.Customer})
	}
	if p.Total != s.Total {
		changes = append(changes, drel.FieldChange{Column: "total", Value: p.Total})
	}
	return changes
}

func orderPKValue(p *Order) any {
	return p.ID()
}

func orderColumnValue(p *Order, idx int) any {
	switch idx {
	case 0:
		return p.ID()
	case 1:
		return p.Customer
	case 2:
		return p.Total
	case 3:
		return p.CreatedAt()
	case 4:
		return p.UpdatedAt()
	}
	return nil
}

func orderInsertColumns(p *Order) ([]string, []any) {
	return []string{"customer", "total"}, []any{p.Customer, p.Total}
}

func orderScanReturning(p *Order, row drel.Row) error {
	idPtr, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	return row.Scan(idPtr, createdAtPtr, updatedAtPtr)
}

func orderNormalizeKey(v any) any {
	return drel.NormalizeUUIDKey(v)
}

func orderKeyIsZero(p *Order) bool {
	var zero uuid.UUID
	return p.ID() == zero
}

func orderScanGenerated(p *Order, row drel.Row) error {
	_, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	return row.Scan(createdAtPtr, updatedAtPtr)
}

var OrderMeta = drel.ModelMeta[Order]{
	Table:         "orders",
	Columns:       []string{"id", "customer", "total", "created_at", "updated_at"},
	PKColumn:      "id",
	Scan:          scanOrder,
	Snapshot:      snapshotOrder,
	Diff:          diffOrder,
	PKValue:       orderPKValue,
	InsertColumns: orderInsertColumns,
	ScanReturning: orderScanReturning,
	ColumnValue:   orderColumnValue,
	NormalizeKey:  orderNormalizeKey,
	KeyStrategy:   drel.KeyAppAssigned,
	GenerateKey:   drel.UUIDv7Key,
	SetKey:        func(p *Order, key any) { p.SetID(key.(uuid.UUID)) },
	KeyIsZero:     orderKeyIsZero,
	ScanGenerated: orderScanGenerated,
}

type OrderRepository struct {
	*drel.Repository[Order]
}

func (r *OrderRepository) FindByID(ctx context.Context, id uuid.UUID) (*Order, error) {
	return r.Find(ctx, id)
}

type TxOrderRepository struct {
	*drel.TxRepository[Order]
}

func (r *TxOrderRepository) FindByID(ctx context.Context, id uuid.UUID) (*Order, error) {
	return r.Find(ctx, id)
}

type UoWOrderRepository struct {
	*drel.UoWRepository[Order]
}

func (r *UoWOrderRepository) FindByID(ctx context.Context, id uuid.UUID) (*Order, error) {
	return r.Find(ctx, id)
}
