// Code generated by drel. DO NOT EDIT.

package db

import (
	"github.com/alternayte/drel"
	models "github.com/alternayte/drel/examples/getting-started/models"
)

type DB struct {
	*drel.Engine
	Tasks *drel.Repository[models.Task]
}

func Open(dsn string, opts ...drel.Option) (*DB, error) {
	engine, err := drel.NewEngine(dsn, opts...)
	if err != nil {
		return nil, err
	}
	return &DB{
		Engine: engine,
		Tasks: drel.NewRepository(engine, models.TaskMeta),
	}, nil
}
