// Code generated by drel. DO NOT EDIT.

package catalog

import (
	"context"
	"time"

	"github.com/alternayte/drel"
)

var Products = struct {
	ID        drel.OrderedColumn[int]
	Name      drel.StringColumn
	Price     drel.OrderedColumn[int]
	CreatedAt drel.Column[time.Time]
	UpdatedAt drel.Column[time.Time]
}{
	ID:        drel.NewOrderedCol[int]("id"),
	Name:      drel.NewStringCol("name"),
	Price:     drel.NewOrderedCol[int]("price"),
	CreatedAt: drel.NewCol[time.Time]("created_at"),
	UpdatedAt: drel.NewCol[time.Time]("updated_at"),
}

func scanProduct(row drel.Row) (*Product, error) {
	p := &Product{}
	idPtr, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	err := row.Scan(idPtr, &p.Name, &p.Price, createdAtPtr, updatedAtPtr)
	if err != nil {
		return nil, err
	}
	return p, nil
}

type productSnapshot struct {
	Name  string
	Price int
}

func snapshotProduct(p *Product) any {
	return productSnapshot{Name: p.Name, Price: p.Price}
}

func diffProduct(p *Product, snap any) []drel.FieldChange {
	s := snap.(productSnapshot)
	var changes []drel.FieldChange
	if p.Name != s.Name {
		changes = append(changes, drel.FieldChange{Column: "name", Value: p.Name})
	}
	if p.Price != s.Price {
		changes = append(changes, drel.FieldChange{Column: "price", Value: p.Price})
	}
	return changes
}

func productPKValue(p *Product) any {
	return p.ID()
}

func productColumnValue(p *Product, idx int) any {
	switch idx {
	case 0:
		return p.ID()
	case 1:
		return p.Name
	case 2:
		return p.Price
	case 3:
		return p.CreatedAt()
	case 4:
		return p.UpdatedAt()
	}
	return nil
}

func productInsertColumns(p *Product) ([]string, []any) {
	return []string{"name", "price"}, []any{p.Name, p.Price}
}

func productScanReturning(p *Product, row drel.Row) error {
	idPtr, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	return row.Scan(idPtr, createdAtPtr, updatedAtPtr)
}

var ProductMeta = drel.ModelMeta[Product]{
	Table:         "products",
	Columns:       []string{"id", "name", "price", "created_at", "updated_at"},
	PKColumn:      "id",
	Scan:          scanProduct,
	Snapshot:      snapshotProduct,
	Diff:          diffProduct,
	PKValue:       productPKValue,
	InsertColumns: productInsertColumns,
	ScanReturning: productScanReturning,
	ColumnValue:   productColumnValue,
}

type ProductRepository struct {
	*drel.Repository[Product]
}

func (r *ProductRepository) FindByID(ctx context.Context, id int) (*Product, error) {
	return r.Find(ctx, id)
}

type TxProductRepository struct {
	*drel.TxRepository[Product]
}

func (r *TxProductRepository) FindByID(ctx context.Context, id int) (*Product, error) {
	return r.Find(ctx, id)
}

type UoWProductRepository struct {
	*drel.UoWRepository[Product]
}

func (r *UoWProductRepository) FindByID(ctx context.Context, id int) (*Product, error) {
	return r.Find(ctx, id)
}
