// Code generated by drel. DO NOT EDIT.

package db

import (
	"github.com/alternayte/drel"
	accounts "github.com/alternayte/drel/examples/value-objects/accounts"
)

type DB struct {
	*drel.Engine
	Accounts *accounts.AccountRepository
}

func Open(dsn string, opts ...drel.Option) (*DB, error) {
	engine, err := drel.NewEngine(dsn, opts...)
	if err != nil {
		return nil, err
	}
	return &DB{
		Engine:   engine,
		Accounts: &accounts.AccountRepository{Repository: drel.NewRepository(engine, accounts.AccountMeta)},
	}, nil
}

// UnitOfWork is a change-tracking work session with typed, tracked
// repositories. Load through uow.<Model>, stage with Add/Remove, then
// SaveChanges to flush everything in a single transaction.
type UnitOfWork struct {
	*drel.UnitOfWork
	Accounts *accounts.UoWAccountRepository
}

// NewUnitOfWork starts a new change-tracking work session.
func (db *DB) NewUnitOfWork() *UnitOfWork {
	uow := db.Engine.NewUnitOfWork()
	return &UnitOfWork{
		UnitOfWork: uow,
		Accounts:   &accounts.UoWAccountRepository{UoWRepository: drel.NewUoWRepository(uow, accounts.AccountMeta)},
	}
}
