// Code generated by drel. DO NOT EDIT.

package models

import (
	"context"
	"time"

	"github.com/alternayte/drel"
)

var Accounts = struct {
	ID        drel.OrderedColumn[int]
	Name      drel.StringColumn
	Role      drel.Column[Role]
	Priority  drel.Column[Priority]
	CreatedAt drel.Column[time.Time]
	UpdatedAt drel.Column[time.Time]
}{
	ID:        drel.NewOrderedCol[int]("id"),
	Name:      drel.NewStringCol("name"),
	Role:      drel.NewCol[Role]("role"),
	Priority:  drel.NewCol[Priority]("priority"),
	CreatedAt: drel.NewCol[time.Time]("created_at"),
	UpdatedAt: drel.NewCol[time.Time]("updated_at"),
}

func RoleValues() []Role {
	return []Role{Role("admin"), Role("user"), Role("guest")}
}

func (r Role) IsValid() bool {
	for _, v := range RoleValues() {
		if r == v {
			return true
		}
	}
	return false
}

func PriorityValues() []Priority {
	return []Priority{Priority(0), Priority(1), Priority(2)}
}

func (r Priority) IsValid() bool {
	for _, v := range PriorityValues() {
		if r == v {
			return true
		}
	}
	return false
}

func scanAccount(row drel.Row) (*Account, error) {
	p := &Account{}
	idPtr, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	err := row.Scan(idPtr, &p.Name, &p.Role, &p.Priority, createdAtPtr, updatedAtPtr)
	if err != nil {
		return nil, err
	}
	return p, nil
}

type accountSnapshot struct {
	Name     string
	Role     Role
	Priority Priority
}

func snapshotAccount(p *Account) any {
	return accountSnapshot{Name: p.Name, Role: p.Role, Priority: p.Priority}
}

func diffAccount(p *Account, snap any) []drel.FieldChange {
	s := snap.(accountSnapshot)
	var changes []drel.FieldChange
	if p.Name != s.Name {
		changes = append(changes, drel.FieldChange{Column: "name", Value: p.Name})
	}
	if p.Role != s.Role {
		changes = append(changes, drel.FieldChange{Column: "role", Value: p.Role})
	}
	if p.Priority != s.Priority {
		changes = append(changes, drel.FieldChange{Column: "priority", Value: p.Priority})
	}
	return changes
}

func accountPKValue(p *Account) any {
	return p.ID()
}

func accountColumnValue(p *Account, idx int) any {
	switch idx {
	case 0:
		return p.ID()
	case 1:
		return p.Name
	case 2:
		return p.Role
	case 3:
		return p.Priority
	case 4:
		return p.CreatedAt()
	case 5:
		return p.UpdatedAt()
	}
	return nil
}

func accountInsertColumns(p *Account) ([]string, []any) {
	return []string{"name", "role", "priority"}, []any{p.Name, p.Role, p.Priority}
}

func accountScanReturning(p *Account, row drel.Row) error {
	idPtr, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	return row.Scan(idPtr, createdAtPtr, updatedAtPtr)
}

func accountNormalizeKey(v any) any {
	return drel.NormalizeIntKey(v)
}

var AccountMeta = drel.ModelMeta[Account]{
	Table:         "accounts",
	Columns:       []string{"id", "name", "role", "priority", "created_at", "updated_at"},
	PKColumn:      "id",
	Scan:          scanAccount,
	Snapshot:      snapshotAccount,
	Diff:          diffAccount,
	PKValue:       accountPKValue,
	InsertColumns: accountInsertColumns,
	ScanReturning: accountScanReturning,
	ColumnValue:   accountColumnValue,
	NormalizeKey:  accountNormalizeKey,
}

type AccountRepository struct {
	*drel.Repository[Account]
}

func (r *AccountRepository) FindByID(ctx context.Context, id int) (*Account, error) {
	return r.Find(ctx, id)
}

type TxAccountRepository struct {
	*drel.TxRepository[Account]
}

func (r *TxAccountRepository) FindByID(ctx context.Context, id int) (*Account, error) {
	return r.Find(ctx, id)
}

type UoWAccountRepository struct {
	*drel.UoWRepository[Account]
}

func (r *UoWAccountRepository) FindByID(ctx context.Context, id int) (*Account, error) {
	return r.Find(ctx, id)
}
