// Code generated by drel. DO NOT EDIT.

package db

import (
	"github.com/alternayte/drel"
	articles "github.com/alternayte/drel/examples/model-features/articles"
)

type DB struct {
	*drel.Engine
	Articles *articles.ArticleRepository
}

func Open(dsn string, opts ...drel.Option) (*DB, error) {
	engine, err := drel.NewEngine(dsn, opts...)
	if err != nil {
		return nil, err
	}
	return &DB{
		Engine:   engine,
		Articles: &articles.ArticleRepository{Repository: drel.NewRepository(engine, articles.ArticleMeta)},
	}, nil
}
