// Code generated by drel. DO NOT EDIT.

package users

import (
	"time"

	"github.com/alternayte/drel"
)

var Users = struct {
	ID drel.OrderedColumn[int]
	Name drel.StringColumn
	Balance drel.OrderedColumn[int]
	CreatedAt drel.Column[time.Time]
	UpdatedAt drel.Column[time.Time]
}{
	ID: drel.NewOrderedCol[int]("id"),
	Name: drel.NewStringCol("name"),
	Balance: drel.NewOrderedCol[int]("balance"),
	CreatedAt: drel.NewCol[time.Time]("created_at"),
	UpdatedAt: drel.NewCol[time.Time]("updated_at"),
}

func scanUser(row drel.Row) (*User, error) {
	p := &User{}
	idPtr, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	err := row.Scan(idPtr, &p.name, &p.balance, createdAtPtr, updatedAtPtr)
	if err != nil {
		return nil, err
	}
	return p, nil
}

type userSnapshot struct {
	name string
	balance int
}

func snapshotUser(p *User) any {
	return userSnapshot{name: p.name, balance: p.balance}
}

func diffUser(p *User, snap any) []drel.FieldChange {
	s := snap.(userSnapshot)
	var changes []drel.FieldChange
	if p.name != s.name {
		changes = append(changes, drel.FieldChange{Column: "name", Value: p.name})
	}
	if p.balance != s.balance {
		changes = append(changes, drel.FieldChange{Column: "balance", Value: p.balance})
	}
	return changes
}

func userPKValue(p *User) any {
	return p.ID()
}

func userInsertColumns(p *User) ([]string, []any) {
	return []string{"name", "balance"}, []any{p.name, p.balance}
}

func userScanReturning(p *User, row drel.Row) error {
	idPtr, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	return row.Scan(idPtr, createdAtPtr, updatedAtPtr)
}

var UserMeta = drel.ModelMeta[User]{
	Table:   "users",
	Columns: []string{"id", "name", "balance", "created_at", "updated_at"},
	PKColumn: "id",
	Scan:          scanUser,
	Snapshot:      snapshotUser,
	Diff:          diffUser,
	PKValue:       userPKValue,
	InsertColumns: userInsertColumns,
	ScanReturning: userScanReturning,
}
