// Code generated by drel. DO NOT EDIT.

package models

import (
	"time"

	"github.com/alternayte/drel"
)

var Tasks = struct {
	ID drel.OrderedColumn[int]
	Title drel.StringColumn
	Done drel.BoolColumn
	Priority drel.OrderedColumn[int]
	CreatedAt drel.Column[time.Time]
	UpdatedAt drel.Column[time.Time]
}{
	ID: drel.NewOrderedCol[int]("id"),
	Title: drel.NewStringCol("title"),
	Done: drel.NewBoolCol("done"),
	Priority: drel.NewOrderedCol[int]("priority"),
	CreatedAt: drel.NewCol[time.Time]("created_at"),
	UpdatedAt: drel.NewCol[time.Time]("updated_at"),
}

func scanTask(row drel.Row) (*Task, error) {
	p := &Task{}
	idPtr, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	err := row.Scan(idPtr, &p.title, &p.done, &p.priority, createdAtPtr, updatedAtPtr)
	if err != nil {
		return nil, err
	}
	return p, nil
}

type taskSnapshot struct {
	title string
	done bool
	priority int
}

func snapshotTask(p *Task) any {
	return taskSnapshot{title: p.title, done: p.done, priority: p.priority}
}

func diffTask(p *Task, snap any) []drel.FieldChange {
	s := snap.(taskSnapshot)
	var changes []drel.FieldChange
	if p.title != s.title {
		changes = append(changes, drel.FieldChange{Column: "title", Value: p.title})
	}
	if p.done != s.done {
		changes = append(changes, drel.FieldChange{Column: "done", Value: p.done})
	}
	if p.priority != s.priority {
		changes = append(changes, drel.FieldChange{Column: "priority", Value: p.priority})
	}
	return changes
}

func taskPKValue(p *Task) any {
	return p.ID()
}

func taskColumnValue(p *Task, idx int) any {
	switch idx {
	case 0:
		return p.ID()
	case 1:
		return p.title
	case 2:
		return p.done
	case 3:
		return p.priority
	case 4:
		return p.CreatedAt()
	case 5:
		return p.UpdatedAt()
	}
	return nil
}

func taskInsertColumns(p *Task) ([]string, []any) {
	return []string{"title", "done", "priority"}, []any{p.title, p.done, p.priority}
}

func taskScanReturning(p *Task, row drel.Row) error {
	idPtr, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	return row.Scan(idPtr, createdAtPtr, updatedAtPtr)
}

var TaskMeta = drel.ModelMeta[Task]{
	Table:   "tasks",
	Columns: []string{"id", "title", "done", "priority", "created_at", "updated_at"},
	PKColumn: "id",
	Scan:          scanTask,
	Snapshot:      snapshotTask,
	Diff:          diffTask,
	PKValue:       taskPKValue,
	InsertColumns: taskInsertColumns,
	ScanReturning: taskScanReturning,
	ColumnValue:   taskColumnValue,
}
