// Code generated by drel. DO NOT EDIT.

package logs

import (
	"context"
	"time"

	"github.com/alternayte/drel"
)

var LogEntries = struct {
	ID drel.OrderedColumn[int]
	Level drel.StringColumn
	Message drel.StringColumn
	CreatedAt drel.Column[time.Time]
	UpdatedAt drel.Column[time.Time]
}{
	ID: drel.NewOrderedCol[int]("id"),
	Level: drel.NewStringCol("level"),
	Message: drel.NewStringCol("message"),
	CreatedAt: drel.NewCol[time.Time]("created_at"),
	UpdatedAt: drel.NewCol[time.Time]("updated_at"),
}

func scanLogentry(row drel.Row) (*LogEntry, error) {
	p := &LogEntry{}
	idPtr, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	err := row.Scan(idPtr, &p.Level, &p.Message, createdAtPtr, updatedAtPtr)
	if err != nil {
		return nil, err
	}
	return p, nil
}

type logentrySnapshot struct {
	Level string
	Message string
}

func snapshotLogentry(p *LogEntry) any {
	return logentrySnapshot{Level: p.Level, Message: p.Message}
}

func diffLogentry(p *LogEntry, snap any) []drel.FieldChange {
	s := snap.(logentrySnapshot)
	var changes []drel.FieldChange
	if p.Level != s.Level {
		changes = append(changes, drel.FieldChange{Column: "level", Value: p.Level})
	}
	if p.Message != s.Message {
		changes = append(changes, drel.FieldChange{Column: "message", Value: p.Message})
	}
	return changes
}

func logentryPKValue(p *LogEntry) any {
	return p.ID()
}

func logentryColumnValue(p *LogEntry, idx int) any {
	switch idx {
	case 0:
		return p.ID()
	case 1:
		return p.Level
	case 2:
		return p.Message
	case 3:
		return p.CreatedAt()
	case 4:
		return p.UpdatedAt()
	}
	return nil
}

func logentryInsertColumns(p *LogEntry) ([]string, []any) {
	return []string{"level", "message"}, []any{p.Level, p.Message}
}

func logentryScanReturning(p *LogEntry, row drel.Row) error {
	idPtr, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	return row.Scan(idPtr, createdAtPtr, updatedAtPtr)
}

var LogEntryMeta = drel.ModelMeta[LogEntry]{
	Table:   "log_entries",
	Columns: []string{"id", "level", "message", "created_at", "updated_at"},
	PKColumn: "id",
	Scan:          scanLogentry,
	Snapshot:      snapshotLogentry,
	Diff:          diffLogentry,
	PKValue:       logentryPKValue,
	InsertColumns: logentryInsertColumns,
	ScanReturning: logentryScanReturning,
	ColumnValue:   logentryColumnValue,
}

type LogEntryRepository struct {
	*drel.Repository[LogEntry]
}

func (r *LogEntryRepository) FindByID(ctx context.Context, id int) (*LogEntry, error) {
	return r.Find(ctx, id)
}

type TxLogEntryRepository struct {
	*drel.TxRepository[LogEntry]
}

func (r *TxLogEntryRepository) FindByID(ctx context.Context, id int) (*LogEntry, error) {
	return r.Find(ctx, id)
}
