// Code generated by drel. DO NOT EDIT.

package products

import (
	"time"

	"github.com/alternayte/drel"
)

var Products = struct {
	ID drel.OrderedColumn[int]
	Name drel.StringColumn
	Price drel.OrderedColumn[int]
	Category drel.StringColumn
	InStock drel.BoolColumn
	CreatedAt drel.Column[time.Time]
	UpdatedAt drel.Column[time.Time]
}{
	ID: drel.NewOrderedCol[int]("id"),
	Name: drel.NewStringCol("name"),
	Price: drel.NewOrderedCol[int]("price"),
	Category: drel.NewStringCol("category"),
	InStock: drel.NewBoolCol("in_stock"),
	CreatedAt: drel.NewCol[time.Time]("created_at"),
	UpdatedAt: drel.NewCol[time.Time]("updated_at"),
}

func scanProduct(row drel.Row) (*Product, error) {
	p := &Product{}
	idPtr, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	err := row.Scan(idPtr, &p.Name, &p.Price, &p.Category, &p.InStock, createdAtPtr, updatedAtPtr)
	if err != nil {
		return nil, err
	}
	return p, nil
}

type productSnapshot struct {
	Name string
	Price int
	Category string
	InStock bool
}

func snapshotProduct(p *Product) any {
	return productSnapshot{Name: p.Name, Price: p.Price, Category: p.Category, InStock: p.InStock}
}

func diffProduct(p *Product, snap any) []drel.FieldChange {
	s := snap.(productSnapshot)
	var changes []drel.FieldChange
	if p.Name != s.Name {
		changes = append(changes, drel.FieldChange{Column: "name", Value: p.Name})
	}
	if p.Price != s.Price {
		changes = append(changes, drel.FieldChange{Column: "price", Value: p.Price})
	}
	if p.Category != s.Category {
		changes = append(changes, drel.FieldChange{Column: "category", Value: p.Category})
	}
	if p.InStock != s.InStock {
		changes = append(changes, drel.FieldChange{Column: "in_stock", Value: p.InStock})
	}
	return changes
}

func productPKValue(p *Product) any {
	return p.ID()
}

func productInsertColumns(p *Product) ([]string, []any) {
	return []string{"name", "price", "category", "in_stock"}, []any{p.Name, p.Price, p.Category, p.InStock}
}

func productScanReturning(p *Product, row drel.Row) error {
	idPtr, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	return row.Scan(idPtr, createdAtPtr, updatedAtPtr)
}

var ProductMeta = drel.ModelMeta[Product]{
	Table:   "products",
	Columns: []string{"id", "name", "price", "category", "in_stock", "created_at", "updated_at"},
	PKColumn: "id",
	Scan:          scanProduct,
	Snapshot:      snapshotProduct,
	Diff:          diffProduct,
	PKValue:       productPKValue,
	InsertColumns: productInsertColumns,
	ScanReturning: productScanReturning,
}
