// Code generated by drel. DO NOT EDIT.

package articles

import (
	"context"
	"maps"
	"slices"
	"time"

	"github.com/alternayte/drel"
)

var Articles = struct {
	ID        drel.OrderedColumn[int]
	Title     drel.StringColumn
	Body      drel.StringColumn
	Tags      drel.ComparableColumn[[]string]
	Metadata  drel.ComparableColumn[map[string]string]
	DeletedAt drel.ComparableColumn[*time.Time]
	Version   drel.OrderedColumn[int]
	CreatedBy drel.StringColumn
	UpdatedBy drel.StringColumn
	CreatedAt drel.TimeColumn
	UpdatedAt drel.TimeColumn
}{
	ID:        drel.NewOrderedCol[int]("id"),
	Title:     drel.NewStringCol("title"),
	Body:      drel.NewStringCol("body"),
	Tags:      drel.NewComparableCol[[]string]("tags"),
	Metadata:  drel.NewComparableCol[map[string]string]("metadata"),
	DeletedAt: drel.NewComparableCol[*time.Time]("deleted_at"),
	Version:   drel.NewOrderedCol[int]("version"),
	CreatedBy: drel.NewStringCol("created_by"),
	UpdatedBy: drel.NewStringCol("updated_by"),
	CreatedAt: drel.NewTimeCol("created_at"),
	UpdatedAt: drel.NewTimeCol("updated_at"),
}

func scanArticle(row drel.Row) (*Article, error) {
	p := &Article{}
	idPtr, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	createdByPtr, updatedByPtr := p.AuditPtrs()
	err := row.Scan(idPtr, &p.Title, &p.Body, drel.JSON[[]string]{V: &p.Tags}, drel.JSON[map[string]string]{V: &p.Metadata}, p.DeletedAtPtr(), p.VersionPtr(), createdByPtr, updatedByPtr, createdAtPtr, updatedAtPtr)
	if err != nil {
		return nil, err
	}
	return p, nil
}

type articleSnapshot struct {
	Title    string
	Body     string
	Tags     []string
	Metadata map[string]string
}

func snapshotArticle(p *Article) any {
	return articleSnapshot{Title: p.Title, Body: p.Body, Tags: p.Tags, Metadata: p.Metadata}
}

func diffArticle(p *Article, snap any) []drel.FieldChange {
	s := snap.(articleSnapshot)
	var changes []drel.FieldChange
	if p.Title != s.Title {
		changes = append(changes, drel.FieldChange{Column: "title", Value: p.Title})
	}
	if p.Body != s.Body {
		changes = append(changes, drel.FieldChange{Column: "body", Value: p.Body})
	}
	if !slices.Equal(p.Tags, s.Tags) {
		changes = append(changes, drel.FieldChange{Column: "tags", Value: drel.JSON[[]string]{V: &p.Tags}})
	}
	if !maps.Equal(p.Metadata, s.Metadata) {
		changes = append(changes, drel.FieldChange{Column: "metadata", Value: drel.JSON[map[string]string]{V: &p.Metadata}})
	}
	return changes
}

func articlePKValue(p *Article) any {
	return p.ID()
}

func articleColumnValue(p *Article, idx int) any {
	switch idx {
	case 0:
		return p.ID()
	case 1:
		return p.Title
	case 2:
		return p.Body
	case 3:
		return drel.JSON[[]string]{V: &p.Tags}
	case 4:
		return drel.JSON[map[string]string]{V: &p.Metadata}
	case 5:
		return p.DeletedAt()
	case 6:
		return p.Version()
	case 7:
		return p.CreatedBy()
	case 8:
		return p.UpdatedBy()
	case 9:
		return p.CreatedAt()
	case 10:
		return p.UpdatedAt()
	}
	return nil
}

func articleInsertColumns(p *Article) ([]string, []any) {
	return []string{"title", "body", "tags", "metadata", "created_by", "updated_by"}, []any{p.Title, p.Body, drel.JSON[[]string]{V: &p.Tags}, drel.JSON[map[string]string]{V: &p.Metadata}, p.CreatedBy(), p.UpdatedBy()}
}

func articleScanReturning(p *Article, row drel.Row) error {
	idPtr, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	return row.Scan(idPtr, createdAtPtr, updatedAtPtr)
}

func articleNormalizeKey(v any) any {
	return drel.NormalizeIntKey(v)
}

var ArticleMeta = drel.ModelMeta[Article]{
	Table:         "articles",
	Columns:       []string{"id", "title", "body", "tags", "metadata", "deleted_at", "version", "created_by", "updated_by", "created_at", "updated_at"},
	PKColumn:      "id",
	Scan:          scanArticle,
	Snapshot:      snapshotArticle,
	Diff:          diffArticle,
	PKValue:       articlePKValue,
	InsertColumns: articleInsertColumns,
	ScanReturning: articleScanReturning,
	ColumnValue:   articleColumnValue,
	NormalizeKey:  articleNormalizeKey,
	HasSoftDelete: true,
	Filters:       []drel.NamedFilter{drel.SoftDeleteFilter},
	HasVersioned:  true,
	VersionValue:  func(p *Article) int { return p.Version() },
	SetVersion:    func(p *Article, v int) { *p.VersionPtr() = v },
	HasAudit:      true,
	AuditSetCreate: func(p *Article, actor string) {
		createdByPtr, updatedByPtr := p.AuditPtrs()
		*createdByPtr = actor
		*updatedByPtr = actor
	},
	AuditSetUpdate: func(p *Article, actor string) {
		_, updatedByPtr := p.AuditPtrs()
		*updatedByPtr = actor
	},
}

type ArticleRepository struct {
	*drel.Repository[Article]
}

func (r *ArticleRepository) FindByID(ctx context.Context, id int) (*Article, error) {
	return r.Find(ctx, id)
}

type TxArticleRepository struct {
	*drel.TxRepository[Article]
}

func (r *TxArticleRepository) FindByID(ctx context.Context, id int) (*Article, error) {
	return r.Find(ctx, id)
}

type UoWArticleRepository struct {
	*drel.UoWRepository[Article]
}

func (r *UoWArticleRepository) FindByID(ctx context.Context, id int) (*Article, error) {
	return r.Find(ctx, id)
}
