// Code generated by drel. DO NOT EDIT.

package articles

import (
	"time"

	"github.com/alternayte/drel"
)

var Articles = struct {
	ID drel.OrderedColumn[int]
	Title drel.StringColumn
	Body drel.StringColumn
	DeletedAt drel.Column[*time.Time]
	Version drel.OrderedColumn[int]
	CreatedBy drel.StringColumn
	UpdatedBy drel.StringColumn
	CreatedAt drel.Column[time.Time]
	UpdatedAt drel.Column[time.Time]
}{
	ID: drel.NewOrderedCol[int]("id"),
	Title: drel.NewStringCol("title"),
	Body: drel.NewStringCol("body"),
	DeletedAt: drel.NewCol[*time.Time]("deleted_at"),
	Version: drel.NewOrderedCol[int]("version"),
	CreatedBy: drel.NewStringCol("created_by"),
	UpdatedBy: drel.NewStringCol("updated_by"),
	CreatedAt: drel.NewCol[time.Time]("created_at"),
	UpdatedAt: drel.NewCol[time.Time]("updated_at"),
}

func scanArticle(row drel.Row) (*Article, error) {
	p := &Article{}
	idPtr, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	createdByPtr, updatedByPtr := p.AuditPtrs()
	err := row.Scan(idPtr, &p.Title, &p.Body, p.DeletedAtPtr(), p.VersionPtr(), createdByPtr, updatedByPtr, createdAtPtr, updatedAtPtr)
	if err != nil {
		return nil, err
	}
	return p, nil
}

type articleSnapshot struct {
	Title string
	Body string
}

func snapshotArticle(p *Article) any {
	return articleSnapshot{Title: p.Title, Body: p.Body}
}

func diffArticle(p *Article, snap any) []drel.FieldChange {
	s := snap.(articleSnapshot)
	var changes []drel.FieldChange
	if p.Title != s.Title {
		changes = append(changes, drel.FieldChange{Column: "title", Value: p.Title})
	}
	if p.Body != s.Body {
		changes = append(changes, drel.FieldChange{Column: "body", Value: p.Body})
	}
	return changes
}

func articlePKValue(p *Article) any {
	return p.ID()
}

func articleColumnValue(p *Article, idx int) any {
	switch idx {
	case 0:
		return p.ID()
	case 1:
		return p.Title
	case 2:
		return p.Body
	case 3:
		return p.DeletedAt()
	case 4:
		return p.Version()
	case 5:
		return p.CreatedBy()
	case 6:
		return p.UpdatedBy()
	case 7:
		return p.CreatedAt()
	case 8:
		return p.UpdatedAt()
	}
	return nil
}

func articleInsertColumns(p *Article) ([]string, []any) {
	return []string{"title", "body", "created_by", "updated_by"}, []any{p.Title, p.Body, p.CreatedBy(), p.UpdatedBy()}
}

func articleScanReturning(p *Article, row drel.Row) error {
	idPtr, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	return row.Scan(idPtr, createdAtPtr, updatedAtPtr)
}

var ArticleMeta = drel.ModelMeta[Article]{
	Table:   "articles",
	Columns: []string{"id", "title", "body", "deleted_at", "version", "created_by", "updated_by", "created_at", "updated_at"},
	PKColumn: "id",
	Scan:          scanArticle,
	Snapshot:      snapshotArticle,
	Diff:          diffArticle,
	PKValue:       articlePKValue,
	InsertColumns: articleInsertColumns,
	ScanReturning: articleScanReturning,
	ColumnValue:   articleColumnValue,
	HasSoftDelete: true,
	Filters: []drel.NamedFilter{drel.SoftDeleteFilter},
	HasVersioned: true,
	VersionValue: func(p *Article) int { return p.Version() },
	SetVersion:   func(p *Article, v int) { *p.VersionPtr() = v },
	HasAudit: true,
	AuditSetCreate: func(p *Article, actor string) {
		createdByPtr, updatedByPtr := p.AuditPtrs()
		*createdByPtr = actor
		*updatedByPtr = actor
	},
	AuditSetUpdate: func(p *Article, actor string) {
		_, updatedByPtr := p.AuditPtrs()
		*updatedByPtr = actor
	},
}
