// Code generated by drel. DO NOT EDIT.

package models

import (
	"context"
	"time"

	"github.com/alternayte/drel"
)

var Authors = struct {
	ID        drel.OrderedColumn[int]
	Name      drel.StringColumn
	CreatedAt drel.Column[time.Time]
	UpdatedAt drel.Column[time.Time]
}{
	ID:        drel.NewOrderedCol[int]("id"),
	Name:      drel.NewStringCol("name"),
	CreatedAt: drel.NewCol[time.Time]("created_at"),
	UpdatedAt: drel.NewCol[time.Time]("updated_at"),
}

func scanAuthor(row drel.Row) (*Author, error) {
	p := &Author{}
	idPtr, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	err := row.Scan(idPtr, &p.Name, createdAtPtr, updatedAtPtr)
	if err != nil {
		return nil, err
	}
	return p, nil
}

type authorSnapshot struct {
	Name string
}

func snapshotAuthor(p *Author) any {
	return authorSnapshot{Name: p.Name}
}

func diffAuthor(p *Author, snap any) []drel.FieldChange {
	s := snap.(authorSnapshot)
	var changes []drel.FieldChange
	if p.Name != s.Name {
		changes = append(changes, drel.FieldChange{Column: "name", Value: p.Name})
	}
	return changes
}

func authorPKValue(p *Author) any {
	return p.ID()
}

func authorColumnValue(p *Author, idx int) any {
	switch idx {
	case 0:
		return p.ID()
	case 1:
		return p.Name
	case 2:
		return p.CreatedAt()
	case 3:
		return p.UpdatedAt()
	}
	return nil
}

func authorInsertColumns(p *Author) ([]string, []any) {
	return []string{"name"}, []any{p.Name}
}

func authorScanReturning(p *Author, row drel.Row) error {
	idPtr, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	return row.Scan(idPtr, createdAtPtr, updatedAtPtr)
}

func authorNormalizeKey(v any) any {
	return drel.NormalizeIntKey(v)
}

var AuthorMeta = drel.ModelMeta[Author]{
	Table:         "authors",
	Columns:       []string{"id", "name", "created_at", "updated_at"},
	PKColumn:      "id",
	Scan:          scanAuthor,
	Snapshot:      snapshotAuthor,
	Diff:          diffAuthor,
	PKValue:       authorPKValue,
	InsertColumns: authorInsertColumns,
	ScanReturning: authorScanReturning,
	ColumnValue:   authorColumnValue,
	NormalizeKey:  authorNormalizeKey,
}

type AuthorRepository struct {
	*drel.Repository[Author]
}

func (r *AuthorRepository) FindByID(ctx context.Context, id int) (*Author, error) {
	return r.Find(ctx, id)
}

type TxAuthorRepository struct {
	*drel.TxRepository[Author]
}

func (r *TxAuthorRepository) FindByID(ctx context.Context, id int) (*Author, error) {
	return r.Find(ctx, id)
}

type UoWAuthorRepository struct {
	*drel.UoWRepository[Author]
}

func (r *UoWAuthorRepository) FindByID(ctx context.Context, id int) (*Author, error) {
	return r.Find(ctx, id)
}
