// Code generated by drel. DO NOT EDIT.

package models

import (
	"time"

	"github.com/alternayte/drel"
)

var AuthorProfiles = struct {
	ID drel.OrderedColumn[int]
	Bio drel.StringColumn
	AuthorID drel.OrderedColumn[int]
	CreatedAt drel.Column[time.Time]
	UpdatedAt drel.Column[time.Time]
}{
	ID: drel.NewOrderedCol[int]("id"),
	Bio: drel.NewStringCol("bio"),
	AuthorID: drel.NewOrderedCol[int]("author_id"),
	CreatedAt: drel.NewCol[time.Time]("created_at"),
	UpdatedAt: drel.NewCol[time.Time]("updated_at"),
}

func scanAuthorprofile(row drel.Row) (*AuthorProfile, error) {
	p := &AuthorProfile{}
	idPtr, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	err := row.Scan(idPtr, &p.Bio, &p.AuthorID, createdAtPtr, updatedAtPtr)
	if err != nil {
		return nil, err
	}
	return p, nil
}

type authorprofileSnapshot struct {
	Bio string
	AuthorID int
}

func snapshotAuthorprofile(p *AuthorProfile) any {
	return authorprofileSnapshot{Bio: p.Bio, AuthorID: p.AuthorID}
}

func diffAuthorprofile(p *AuthorProfile, snap any) []drel.FieldChange {
	s := snap.(authorprofileSnapshot)
	var changes []drel.FieldChange
	if p.Bio != s.Bio {
		changes = append(changes, drel.FieldChange{Column: "bio", Value: p.Bio})
	}
	if p.AuthorID != s.AuthorID {
		changes = append(changes, drel.FieldChange{Column: "author_id", Value: p.AuthorID})
	}
	return changes
}

func authorprofilePKValue(p *AuthorProfile) any {
	return p.ID()
}

func authorprofileColumnValue(p *AuthorProfile, idx int) any {
	switch idx {
	case 0:
		return p.ID()
	case 1:
		return p.Bio
	case 2:
		return p.AuthorID
	case 3:
		return p.CreatedAt()
	case 4:
		return p.UpdatedAt()
	}
	return nil
}

func authorprofileInsertColumns(p *AuthorProfile) ([]string, []any) {
	return []string{"bio", "author_id"}, []any{p.Bio, p.AuthorID}
}

func authorprofileScanReturning(p *AuthorProfile, row drel.Row) error {
	idPtr, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	return row.Scan(idPtr, createdAtPtr, updatedAtPtr)
}

var AuthorProfileMeta = drel.ModelMeta[AuthorProfile]{
	Table:   "author_profiles",
	Columns: []string{"id", "bio", "author_id", "created_at", "updated_at"},
	PKColumn: "id",
	Scan:          scanAuthorprofile,
	Snapshot:      snapshotAuthorprofile,
	Diff:          diffAuthorprofile,
	PKValue:       authorprofilePKValue,
	InsertColumns: authorprofileInsertColumns,
	ScanReturning: authorprofileScanReturning,
	ColumnValue:   authorprofileColumnValue,
}
