// Code generated by drel. DO NOT EDIT.

package models

import (
	"context"
	"time"

	"github.com/alternayte/drel"
)

var Books = struct {
	ID        drel.OrderedColumn[int]
	Title     drel.StringColumn
	AuthorID  drel.OrderedColumn[int]
	CreatedAt drel.Column[time.Time]
	UpdatedAt drel.Column[time.Time]
}{
	ID:        drel.NewOrderedCol[int]("id"),
	Title:     drel.NewStringCol("title"),
	AuthorID:  drel.NewOrderedCol[int]("author_id"),
	CreatedAt: drel.NewCol[time.Time]("created_at"),
	UpdatedAt: drel.NewCol[time.Time]("updated_at"),
}

func scanBook(row drel.Row) (*Book, error) {
	p := &Book{}
	idPtr, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	err := row.Scan(idPtr, &p.Title, &p.AuthorID, createdAtPtr, updatedAtPtr)
	if err != nil {
		return nil, err
	}
	return p, nil
}

type bookSnapshot struct {
	Title    string
	AuthorID int
}

func snapshotBook(p *Book) any {
	return bookSnapshot{Title: p.Title, AuthorID: p.AuthorID}
}

func diffBook(p *Book, snap any) []drel.FieldChange {
	s := snap.(bookSnapshot)
	var changes []drel.FieldChange
	if p.Title != s.Title {
		changes = append(changes, drel.FieldChange{Column: "title", Value: p.Title})
	}
	if p.AuthorID != s.AuthorID {
		changes = append(changes, drel.FieldChange{Column: "author_id", Value: p.AuthorID})
	}
	return changes
}

func bookPKValue(p *Book) any {
	return p.ID()
}

func bookColumnValue(p *Book, idx int) any {
	switch idx {
	case 0:
		return p.ID()
	case 1:
		return p.Title
	case 2:
		return p.AuthorID
	case 3:
		return p.CreatedAt()
	case 4:
		return p.UpdatedAt()
	}
	return nil
}

func bookInsertColumns(p *Book) ([]string, []any) {
	return []string{"title", "author_id"}, []any{p.Title, p.AuthorID}
}

func bookScanReturning(p *Book, row drel.Row) error {
	idPtr, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	return row.Scan(idPtr, createdAtPtr, updatedAtPtr)
}

var BookMeta = drel.ModelMeta[Book]{
	Table:         "books",
	Columns:       []string{"id", "title", "author_id", "created_at", "updated_at"},
	PKColumn:      "id",
	Scan:          scanBook,
	Snapshot:      snapshotBook,
	Diff:          diffBook,
	PKValue:       bookPKValue,
	InsertColumns: bookInsertColumns,
	ScanReturning: bookScanReturning,
	ColumnValue:   bookColumnValue,
}

type BookRepository struct {
	*drel.Repository[Book]
}

func (r *BookRepository) FindByID(ctx context.Context, id int) (*Book, error) {
	return r.Find(ctx, id)
}

type TxBookRepository struct {
	*drel.TxRepository[Book]
}

func (r *TxBookRepository) FindByID(ctx context.Context, id int) (*Book, error) {
	return r.Find(ctx, id)
}
