// Code generated by drel. DO NOT EDIT.

package models

import (
	"context"
	"time"

	"github.com/alternayte/drel"
)

var Notes = struct {
	ID        drel.OrderedColumn[int]
	Slug      drel.StringColumn
	Title     drel.StringColumn
	Category  drel.StringColumn
	Pinned    drel.BoolColumn
	CreatedAt drel.Column[time.Time]
	UpdatedAt drel.Column[time.Time]
}{
	ID:        drel.NewOrderedCol[int]("id"),
	Slug:      drel.NewStringCol("slug"),
	Title:     drel.NewStringCol("title"),
	Category:  drel.NewStringCol("category"),
	Pinned:    drel.NewBoolCol("pinned"),
	CreatedAt: drel.NewCol[time.Time]("created_at"),
	UpdatedAt: drel.NewCol[time.Time]("updated_at"),
}

func scanNote(row drel.Row) (*Note, error) {
	p := &Note{}
	idPtr, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	err := row.Scan(idPtr, &p.Slug, &p.Title, &p.Category, &p.Pinned, createdAtPtr, updatedAtPtr)
	if err != nil {
		return nil, err
	}
	return p, nil
}

type noteSnapshot struct {
	Slug     string
	Title    string
	Category string
	Pinned   bool
}

func snapshotNote(p *Note) any {
	return noteSnapshot{Slug: p.Slug, Title: p.Title, Category: p.Category, Pinned: p.Pinned}
}

func diffNote(p *Note, snap any) []drel.FieldChange {
	s := snap.(noteSnapshot)
	var changes []drel.FieldChange
	if p.Slug != s.Slug {
		changes = append(changes, drel.FieldChange{Column: "slug", Value: p.Slug})
	}
	if p.Title != s.Title {
		changes = append(changes, drel.FieldChange{Column: "title", Value: p.Title})
	}
	if p.Category != s.Category {
		changes = append(changes, drel.FieldChange{Column: "category", Value: p.Category})
	}
	if p.Pinned != s.Pinned {
		changes = append(changes, drel.FieldChange{Column: "pinned", Value: p.Pinned})
	}
	return changes
}

func notePKValue(p *Note) any {
	return p.ID()
}

func noteColumnValue(p *Note, idx int) any {
	switch idx {
	case 0:
		return p.ID()
	case 1:
		return p.Slug
	case 2:
		return p.Title
	case 3:
		return p.Category
	case 4:
		return p.Pinned
	case 5:
		return p.CreatedAt()
	case 6:
		return p.UpdatedAt()
	}
	return nil
}

func noteInsertColumns(p *Note) ([]string, []any) {
	return []string{"slug", "title", "category", "pinned"}, []any{p.Slug, p.Title, p.Category, p.Pinned}
}

func noteScanReturning(p *Note, row drel.Row) error {
	idPtr, createdAtPtr, updatedAtPtr := p.ScanPtrs()
	return row.Scan(idPtr, createdAtPtr, updatedAtPtr)
}

func noteNormalizeKey(v any) any {
	return drel.NormalizeIntKey(v)
}

var NoteMeta = drel.ModelMeta[Note]{
	Table:         "notes",
	Columns:       []string{"id", "slug", "title", "category", "pinned", "created_at", "updated_at"},
	PKColumn:      "id",
	Scan:          scanNote,
	Snapshot:      snapshotNote,
	Diff:          diffNote,
	PKValue:       notePKValue,
	InsertColumns: noteInsertColumns,
	ScanReturning: noteScanReturning,
	ColumnValue:   noteColumnValue,
	NormalizeKey:  noteNormalizeKey,
}

type NoteRepository struct {
	*drel.Repository[Note]
}

func (r *NoteRepository) FindByID(ctx context.Context, id int) (*Note, error) {
	return r.Find(ctx, id)
}

type TxNoteRepository struct {
	*drel.TxRepository[Note]
}

func (r *TxNoteRepository) FindByID(ctx context.Context, id int) (*Note, error) {
	return r.Find(ctx, id)
}

type UoWNoteRepository struct {
	*drel.UoWRepository[Note]
}

func (r *UoWNoteRepository) FindByID(ctx context.Context, id int) (*Note, error) {
	return r.Find(ctx, id)
}
